import React,{useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Award,CheckCircle2,ShieldCheck} from 'lucide-react';
import './assessment.css';

async function request(path='',method='GET',body){
 const r=await fetch('/api/assessments'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to save your test');return data;
}
const date=at=>new Date(at).toLocaleDateString();
export function AssessmentSummary({assessment,onOpen,privateResult=false}){
 const result=assessment?.result;
 return <section className="panel assessment-summary"><div><span className="eyebrow">TEST-BASED PLACEMENT · SPANISH</span><h3>{privateResult?'Assessment is private':result?`${result.level} · provisional placement`:'Find your starting point'}</h3><p>{privateResult?'The learner controls sharing in Account.':result?`${result.correct}/${result.total} · ${date(assessment.at)} · Reading and language use only. Not an overall CEFR rating.`:'Take a separate diagnostic test. Completing lessons does not set or raise your assessed level.'}</p></div>{onOpen&&<button className="primary" onClick={onOpen}>{result?'Results & reassessment':'Take placement test'}<ArrowRight size={16}/></button>}</section>;
}
export function AssessmentReport({assessment}){
 if(!assessment?.result)return null;
 const r=assessment.result;
 return <section className="panel assessment-result"><span className="eyebrow">{assessment.kind==='placement'?'PLACEMENT TEST':'REASSESSMENT'} · {date(assessment.at)}</span><div className="assessment-result-top"><div><h2>{r.level}</h2><p>Provisional course placement</p></div><div className="assessment-score"><Award size={24}/><strong>{r.correct}/{r.total}</strong><small>test questions correct</small></div></div><p>Based on reading and language-use tasks across A1–C1 difficulty bands. This is an experimental course recommendation, not a validated CEFR qualification or an overall proficiency rating. C2 is not tested.</p><div className="assessment-skill-grid">{r.skills.map(s=><div key={s.name}><b>{s.name}</b><strong>{s.correct}/{s.total}</strong><small>Diagnostic task score</small></div>)}{['Listening','Speaking','Writing'].map(s=><div key={s}><b>{s}</b><strong>—</strong><small>Not assessed</small></div>)}</div><details><summary>How this result is calculated</summary><p>Each band has 3 reading and 3 language-use questions. Placement is the highest consecutive band with at least 2/3 in each area (4/6 overall), starting at A1. These are provisional product thresholds, not official CEFR cut scores. “Below A1” means the A1 threshold was not met on this sample, not a confirmed Pre-A1 rating. Skipped questions count as incorrect.</p><div className="assessment-table"><table><caption>Evidence by task difficulty</caption><thead><tr><th>Band</th><th>Reading</th><th>Language use</th><th>Total</th></tr></thead><tbody>{r.bands.map(b=><tr key={b.level}><th>{b.level}</th><td>{b.reading}/3</td><td>{b.languageUse}/3</td><td>{b.correct}/6</td></tr>)}</tbody></table></div><p>Skipped: {r.skipped}. Method: {r.method}. A small question sample has uncertainty; use a teacher-led four-skill assessment or a validated exam for higher-stakes decisions.</p><a href="https://www.coe.int/en/web/common-european-framework-reference-languages/relating-examinations-to-the-cefr" target="_blank" rel="noreferrer">About relating tests to CEFR</a></details></section>;
}
export default function Assessment({user,onAccount,onCourse,onUpdated}){
 const [data,setData]=useState(null),[session,setSession]=useState(null),[choice,setChoice]=useState(undefined),[busy,setBusy]=useState(false),[error,setError]=useState(''),[agreed,setAgreed]=useState(false);
 const load=async()=>{setError('');try{setData(await request())}catch(e){setError(e.message)}};
 useEffect(()=>{let live=true;if(user?.role==='learner')request().then(d=>{if(live)setData(d)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[user?.id]);
 const start=async()=>{if(busy)return;setBusy(true);setError('');try{const d=await request('','POST',{});setSession(d.session);setChoice(undefined)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const submit=async()=>{if(busy||choice===undefined)return;setBusy(true);setError('');try{
  const d=await request('/'+session.id,'PUT',{index:session.index,answer:choice});
  if(d.session.result){const finished={id:d.session.id,kind:d.session.kind,version:d.session.version,form:d.session.form,at:d.session.completedAt,result:d.session.result};setData(old=>({...old,active:null,history:[finished,...(old?.history||[]).filter(x=>x.id!==finished.id)]}));setSession(null);onUpdated?.(finished);setAgreed(false);}else setSession(d.session);
  setChoice(undefined);
 }catch(e){setError(e.message)}finally{setBusy(false)}};
 const pause=async()=>{if(busy)return;setSession(null);setChoice(undefined);await load()};
 const errorBox=error&&<div className="auth-error" role="alert"><p>{error}</p><button className="outline-button" disabled={busy} onClick={async()=>{setSession(null);await load()}}>Reload saved test</button></div>;
 if(!user)return <section className="panel assessment-intro"><span className="eyebrow">SPANISH PLACEMENT & REASSESSMENT</span><h1>Know where to begin.</h1><p>Sign in as a learner to take a diagnostic test and keep your results across devices.</p><button className="primary" onClick={onAccount}>Sign in to take the test</button></section>;
 if(!data)return <section className="panel"><h2>Loading your assessments…</h2>{errorBox}</section>;
 if(session){const q=session.question;return <div className="assessment-page"><div className="assessment-test-top"><button className="back" disabled={busy} onClick={pause}><ArrowLeft size={17}/>Pause test</button><span>Question {session.index+1} of {session.total}</span></div><progress aria-label="Test progress" max={session.total} value={session.index}/><section className="panel assessment-question" key={q.id}><span className="eyebrow">{q.skill.toUpperCase()} · SPANISH</span>{q.passage&&<blockquote lang="es">{q.passage}</blockquote>}<h1 lang="es">{q.prompt}</h1><fieldset disabled={busy}><legend>Choose one answer</legend>{q.options.map((option,i)=><label key={i} className={choice===i?'chosen':''}><input type="radio" name={q.id} checked={choice===i} onChange={()=>setChoice(i)}/><span lang="es">{option}</span></label>)}<label className={choice===null?'chosen':''}><input type="radio" name={q.id} checked={choice===null} onChange={()=>setChoice(null)}/><span>I don’t know / skip</span></label></fieldset>{errorBox}<button className="primary wide" disabled={busy||choice===undefined} onClick={submit}>{busy?'Saving…':session.index+1===session.total?'Finish test & update placement':'Save answer & continue'}<ArrowRight size={17}/></button><p className="assessment-small">Each continued answer is saved and cannot be changed. There is no answer feedback during the test. Pause keeps saved answers; the current unsaved choice will be repeated.</p></section></div>}
 const latest=data.history[0],previous=data.history[1];
 return <div className="assessment-page"><section className="assessment-hero"><span className="eyebrow">A CLEARER STARTING POINT</span><h1>Your level, tested.</h1><p>Learning progress shows what you have completed. An assessment gives separate evidence for where to begin next.</p><div className="assessment-chips"><span>Spanish · A1–C1 tasks</span><span>30 questions</span><span>About 20–30 minutes · untimed</span></div></section>{errorBox}{latest&&<><AssessmentReport assessment={latest}/>{previous&&<p className="assessment-comparison">Previous: {previous.result.level} ({date(previous.at)}) → Latest: {latest.result.level} ({date(latest.at)}). The latest complete test replaces your placement, even if lower. Small changes can reflect sampling or familiarity.</p>}<button className="outline-button" onClick={()=>onCourse(latest.result.courseLevel)}>Explore the recommended {latest.result.courseLevel} learning path<ArrowRight size={16}/></button></>}
 <section className="panel assessment-intro"><span className="eyebrow">{data.active?'READY WHEN YOU ARE':latest?'CHECK YOUR PROGRESS':'FIRST-TIME PLACEMENT'}</span><h2>{data.active?'Resume your saved test':latest?'Take a reassessment':'Take your placement test'}</h2><p>Reading comprehension and grammar/vocabulary in context. Listening, speaking and writing are not assessed here; a full CEFR profile still needs those skills.</p><ul><li>Work independently, without a dictionary, translator or outside help.</li><li>Choose “I don’t know” instead of guessing when possible.</li><li>Your first completed test sets your placement; later completed tests update it. An unfinished test never changes your previous result.</li><li>Two alternate forms reduce immediate repetition, but questions recur. They have not been statistically equated or validated. Retake after meaningful study, ideally several weeks, rather than immediately.</li></ul><div className="assessment-privacy"><ShieldCheck size={20}/><p>Results follow “Share self-study activity” in Account. Turning it off hides test results from connected teachers too.</p></div>{data.active?<p>{data.active.index}/{data.active.total} answers saved · Started {date(data.active.startedAt)}</p>:<label className="assessment-consent"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/>I understand this is a provisional reading/language-use diagnostic, not an overall CEFR certification.</label>}<button className="primary" disabled={busy||(!data.active&&!agreed)} onClick={start}>{busy?'Opening…':data.active?'Resume test':latest?'Start reassessment':'Start placement test'}<ArrowRight size={17}/></button></section>
 {data.history.length>0&&<section className="panel assessment-history"><span className="eyebrow">YOUR ASSESSMENT RECORD</span><h2>Test history</h2><p>Most recent 20 results. Lesson scores do not change these results.</p>{data.history.map(h=><article key={h.id}><CheckCircle2 size={19}/><div><b>{h.kind==='placement'?'Placement':'Reassessment'} · {h.result.level}</b><p>{date(h.at)} · {h.result.correct}/{h.result.total} · Form {h.form+1}</p></div><small>{h.id===latest.id?'Current':'Previous'}</small></article>)}</section>}</div>;
}
