import {levelConversationChapters,levelConversationLessons} from './level-conversations.mjs';
import {multilingualConversationChapters,multilingualConversationLessons} from './multilingual-conversations.mjs';
// Original public-domain footage from VOA Learning English; see LESSON-MEDIA.md.
const source='https://learningenglish.voanews.com';
const definitions=[
 {key:'welcome',title:'Meet a new neighbour',goal:'Listen to Anna and Pete introduce themselves, check a name and confirm an address.',page:'/a/lets-learn-english-lesson-one/3111026.html',video:'https://voa-video-ns.akamaized.net/pangeavideo/2021/02/5/5f/5f00c78a-0f84-41e6-949d-bd808bcadf50.mp4',poster:'/lesson-media/voa-welcome.jpg',alt:'Anna and Pete introduce themselves outside an apartment building',
 transcript:[['Pete','Hi! Are you Anna?'],['Anna','Yes! Hi there! Are you Pete?'],['Pete','I am Pete.'],['Anna','Nice to meet you.'],['Anna',"Let’s try that again. I’m Anna. Nice to meet you."],['Pete',"I’m Pete. Anna? Is that A-N-A?"],['Anna','No. A-N-N-A.'],['Pete',"Well, Anna with two n’s … Welcome to … 1400 Irving Street!"],['Anna','My new apartment! Yes!']],
 questions:[['Who welcomes Anna?',['Pete','Jonathan','Marsha'],0,'Pete introduces himself and welcomes Anna.'],['How does Anna spell her name?',['A-N-A','A-N-N-A','A-N-N-E'],1,'Anna corrects the spelling: her name has two n’s.'],['What is the street number?',['140','1401','1400'],2,'Pete welcomes Anna to 1400 Irving Street.'],['Why is Anna there?',['She has a new apartment','She is buying a train ticket','She is applying for a job'],0,'Anna identifies the building as her new apartment.'],['What does “Nice to meet you” do?',['Ends a telephone call','Greets someone at a first meeting','Asks for directions'],1,'It is a friendly expression used when meeting someone.'],['What does “I’m” mean?',['I have','I will','I am'],2,'The apostrophe joins I and am in this contraction.'],['Why does Pete ask about the spelling?',['To check Anna’s name','To ask her age','To find her job'],0,'He checks whether her name has one n or two.'],['Choose a natural response to “Are you Anna?”',['At the station.','Yes, I am.','Yesterday morning.'],1,'A yes/no identity question can be answered with Yes, I am.']]},
 {key:'neighbours',title:'Meet the people in your building',goal:'Follow introductions and distinguish names, apartment numbers and a request.',page:'/a/lets-learn-english-lesson-2-hello/3113733.html',video:'https://voa-video-ns.akamaized.net/pangeavideo/2021/02/4/42/4298a2ba-d665-4b1c-aaa1-502bbcb9b88d.mp4',poster:'/lesson-media/voa-neighbours.jpg',alt:'Anna, Jonathan and Pete talk outside their building',
 transcript:[['Jonathan',"Hey, Pete! Who’s your friend?"],['Pete','She is Anna. She is new to D.C.'],['Jonathan','Where are you from?'],['Anna','I am from a small town.'],['Jonathan','Well, welcome to D.C.'],['Anna','Thank you.'],['Jonathan','I am Jonathan. I am in apartment B4.'],['Anna','I am in apartment C2. Marsha is my roommate.'],['Jonathan','I know Marsha. She is nice.'],['Pete','And I am in apartment D7. I have to go now.'],['Anna','Oh!'],['Pete',"Remember to call Marsha at work. Tell her you’re here."],['Anna','Right, thanks, Pete. Nice to meet you!'],['Jonathan','You too. Bye.'],['Anna','Apartment C2, here I come!']],
 questions:[['Where is Anna from?',['A small town','A large island','The same building'],0,'Anna says she comes from a small town.'],['Which apartment is Anna’s?',['B4','C2','D7'],1,'Anna identifies her apartment as C2.'],['Who lives in apartment B4?',['Pete','Marsha','Jonathan'],2,'Jonathan introduces himself and gives B4 as his apartment.'],['Who is Marsha?',['Anna’s roommate','Pete’s teacher','Jonathan’s sister'],0,'Anna says that Marsha is her roommate.'],['What does Pete ask Anna to do?',['Buy some food','Call Marsha at work','Meet him at the station'],1,'Pete asks Anna to call Marsha and say that she has arrived.'],['Where does Pete live?',['C2','B4','D7'],2,'Pete gives his apartment as D7 before saying goodbye.'],['What information does “Where are you from?” ask for?',['Someone’s origin','Someone’s name','Someone’s phone number'],0,'This question asks where a person comes from.'],['What should Anna tell Marsha?',['That Pete has moved','That Anna is here','That Jonathan is at work'],1,'Pete’s instruction is to tell Marsha that Anna is here.']]}
];
export const conversationChapters=definitions.map(d=>({id:`en-conversation-v1-${d.key}-chapter`,level:'A1',language:'en',locale:'en-US',specialist:true,curriculumVersion:2,title:d.title,goal:d.goal,kind:'Real conversations'}));
export const conversationLessons=definitions.map(d=>({id:`en-conversation-v1-${d.key}`,chapter:`en-conversation-v1-${d.key}-chapter`,level:'A1',language:'en',locale:'en-US',specialist:true,curriculumVersion:2,title:d.title,skill:'Listening',minutes:10,explanation:d.goal+' Watch once for the situation, then replay for names and details. The source video includes teaching pauses and repetition.',example:'Listen first, then answer the questions. Replay whenever you need.',exampleLang:'en-US',conversation:{src:d.video,poster:d.poster,alt:d.alt,source:source+d.page,credit:'VOA Learning English',transcript:d.transcript},questions:d.questions.map(([prompt,options,answer,note])=>({prompt,options,answer,note,video:true}))}));

conversationChapters.push(...multilingualConversationChapters);
conversationLessons.push(...multilingualConversationLessons);

conversationChapters.push(...levelConversationChapters);
conversationLessons.push(...levelConversationLessons);
