import React,{useState,useRef} from 'react';
import {BookOpen,NotebookPen,ChevronRight,ArrowRight,Clock3} from 'lucide-react';
import {languageInfo} from './languages.mjs';
import {lessonList,lessonTitle,getLesson} from './course.mjs';
import {AssessmentSummary} from './Assessment.jsx';
import {SkillRecord} from './SkillsWorkshop.jsx';
import RecurringPatterns from './RecurringPatterns.jsx';
import './learning-memory.css';
const date=x=>new Date(x).toLocaleDateString();
function ScoreRing({score,label}){return <div className="record-score-ring" style={{'--score':(score||0)*3.6+'deg'}}><div><b>{score===null?'—':score+'%'}</b><small>{label}</small></div></div>}
export default function LanguageOverview({language,user,attempts=[],notes=[],assessment,onNavigate,onPractice,memory=false}){
 const name=languageInfo(language).name,ordered=[...attempts].sort((a,b)=>new Date(b.at)-new Date(a.at)),ids=[...new Set(ordered.map(a=>a.lesson))],lessons=lessonList.filter(l=>(l.language||'es')===language),done=new Set(attempts.filter(a=>a.score>=(getLesson(a.lesson)?.passScore||80)).map(a=>a.lesson)),[selected,setSelected]=useState(''),detail=useRef(null);
 const active=ids.includes(selected)?selected:ids[0],history=ordered.filter(a=>a.lesson===active),latest=history[0],recent=ordered[0],first=history.at(-1),events=[...ordered.map((a,i)=>({...a,eventId:'practice-'+(a.id||i),title:lessonTitle(a.lesson),kind:'Practice'})),...notes.map(n=>({...n,eventId:'note-'+n.id,title:n.focus,kind:'Class note'}))].sort((a,b)=>new Date(b.at)-new Date(a.at));
 function select(id){setSelected(id);requestAnimationFrame(()=>detail.current?.scrollIntoView({behavior:'smooth',block:'start'}));}
 return <div className="unified-learning-record"><span className="eyebrow">{name.toUpperCase()} · YOUR LEARNING RECORD</span><h1>{memory?'Learning memory':`${name}: your next step`}</h1><p>{memory?'Your practice, feedback and class observations, connected in one place.':'See where you are, what is improving, and what to practise next.'}</p>
 {!memory&&<AssessmentSummary language={language} assessment={assessment} profile onOpen={()=>onNavigate('Level test')}/>}
 <section className="memory-hero connected-memory-hero"><div><div className="assessment-ring small"><NotebookPen/><b>{attempts.length+notes.length}</b><small>recent records</small></div><span><b>Practice that stays with you</b><small>{name} · your saved learning memory</small></span></div><div className="memory-source"><span><BookOpen size={18}/>{done.size} activities mastered</span><span><NotebookPen size={18}/>{notes.length} class notes</span></div></section>
 {!memory&&<section className="panel record-recent"><div><span className="eyebrow">RECENT PRACTICE</span><h2>{recent?lessonTitle(recent.lesson):'Your next chapter starts here'}</h2><p>{recent?`${recent.total} questions · ${date(recent.at)}`:`Explore ${lessons.length} course activities from A1 to C1.`}</p><button className="primary" onClick={()=>recent?onPractice(recent.lesson):onNavigate('Learn')}>{recent?'Practise again':'Start learning'}<ArrowRight size={17}/></button></div><ScoreRing score={recent?.score??null} label="latest exercise"/></section>}
 <RecurringPatterns key={language+'-'+user?.id+'-'+attempts.length} language={language} user={user} onPractice={onPractice} onNavigate={onNavigate}/>
 {memory?<><div className="memory-layout record-evidence-layout"><section className="panel pattern-list"><span className="eyebrow">LESSON EVIDENCE</span><h2>What you have practised</h2>{ids.length?ids.map(id=>{const a=ordered.find(x=>x.lesson===id);return <button key={id} className={active===id?'active':''} aria-pressed={active===id} aria-controls="selected-lesson-evidence" onClick={()=>select(id)}><div className="record-lesson-label"><b>{lessonTitle(id)}</b><small>{getLesson(id)?.skill||'Practice'}</small></div><strong>{a.score}%</strong><ChevronRight size={18}/></button>}):<p>No completed lessons yet. Your results will appear here after practice.</p>}</section><section id="selected-lesson-evidence" className="panel pattern-detail record-detail" ref={detail} tabIndex={-1} aria-label="Selected lesson evidence">{latest?<><span className="eyebrow">SAVED PRACTICE RESULTS</span><h2>{lessonTitle(active)}</h2><ScoreRing score={latest.score} label="latest exercise"/><div className="growth"><span><small>Earliest saved</small><b>{first.score}%</b></span><ArrowRight/><span><small>Latest saved</small><b>{latest.score}%</b></span></div><p>{history.length} saved attempts · {date(latest.at)}</p><button className="primary" onClick={()=>onPractice(active)}>Practise this lesson<ChevronRight size={17}/></button><details><summary>Score history</summary>{history.map((a,i)=><p key={a.id||i}>{date(a.at)} · {a.score}% · {a.total} questions</p>)}</details></>:<><h2>Your evidence, over time</h2><p>Choose a completed lesson to explore your results.</p></>}</section></div><section className="panel activity"><span className="eyebrow">YOUR LEARNING TIMELINE</span><h2>Lessons and classes, connected</h2><div className="record-timeline">{events.length?events.map(e=><article key={e.eventId}><div className="record-event-icon">{e.kind==='Practice'?<BookOpen size={19}/>:<NotebookPen size={19}/>}</div><div><small>{e.kind} · {date(e.at)}</small><h3>{e.title}</h3>{e.note?<p>{e.note}</p>:<button className="text-button" onClick={()=>select(e.lesson)}>View result · {e.score}%<ChevronRight size={15}/></button>}</div></article>):<p>Your learning timeline will grow with your activity.</p>}</div><small>Showing up to 50 recent lesson attempts and class notes. Recurring patterns counts your complete saved history.</small></section></>:<button className="outline-button" onClick={()=>onNavigate('Learning memory')}>Explore your learning memory<ChevronRight size={17}/></button>}
 {user&&<SkillRecord language={language} user={user}/>}<p className="record-privacy">Teacher visibility follows “Share self-study activity” in Account.</p></div>;
}
