import SentenceAudio,{SpokenText} from './SentenceAudio.jsx';
import React from 'react';
import './lesson-reference.css';
import {expressionGuidance} from './curriculum-expressions.mjs';

export default function LessonReference({lesson}){
 const content=lesson.breakdown;
 if(!content&&!lesson.vocabulary&&!lesson.expressions)return null;
 return <div className="lesson-reference">
 {lesson.expressions&&<section className="expression-toolkit"><span className="eyebrow">CHUNKS → CONTEXT → YOUR OWN WORDS</span><h2>Your expression toolkit</h2><p className="expression-priority">{lesson.priority}</p><p>Learn each phrase as a unit. Notice its register, cover the translation, then use it in a new situation of your own.</p><div className="expression-grid">{lesson.expressions.map(x=><article key={x.term}><div className="expression-tags"><span>{x.type}</span><span>{x.register}</span></div><h3 lang={lesson.locale||'es-ES'}><SpokenText text={x.term} lang={lesson.locale||'es-ES'}/></h3><p><strong><SpokenText text={x.meaning} lang="en-US"/></strong></p><p><b>When & how:</b> <SpokenText text={x.use} lang="auto"/></p><div className="translated-example"><b lang={lesson.locale||'es-ES'}><SpokenText text={x.example} lang={lesson.locale||'es-ES'}/></b><p><SpokenText text={x.translation} lang="en-US"/></p></div><p className="rule-pitfall"><b>Watch out:</b> <SpokenText text={x.pitfall} lang="auto"/></p><small>{x.region}</small></article>)}</div><details className="expression-level-note"><summary>About levels and learning priority</summary><p>{expressionGuidance.note}</p><p>A collocation is a natural word combination; an idiom has a meaning that is not simply literal. Expressions include useful conversational formulas. Categories can overlap.</p><ul>{expressionGuidance.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title}</a></li>)}</ul></details></section>}
 {content&&<>
  <section><span className="eyebrow">BUILD THE RULE</span><h2>How the form works</h2><ol>{content.steps.map(step=><li key={step}><SpokenText text={step} lang="auto"/></li>)}</ol></section>
  {content.tables.map(t=><div key={t.caption} className="conjugation-scroll" tabIndex={0} role="region" aria-label={t.caption+' — scroll horizontally if needed'}><table><caption>{t.caption}</caption><thead><tr>{t.headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{t.rows.map(row=><tr key={row[0]}>{row.map((cell,i)=>i===0?<th key={i} scope="row"><SpokenText text={cell} lang={lesson.locale||'es-ES'}/></th>:<td key={i} lang={lesson.locale||'es-ES'}><SpokenText text={cell} lang={lesson.locale||'es-ES'}/></td>)}</tr>)}</tbody></table></div>)}
  {!lesson.language&&<p className="reference-hint">Tables include vosotros (mainly Spain); ustedes takes the ellos/ellas form. Accent marks matter. Regional voseo forms are outside these tables.</p>}
  <section className="rule-pitfall"><h3>Watch out for this</h3><p><SpokenText text={content.pitfall} lang="auto"/></p></section>
  <section><h3>See the meaning in context</h3>{content.examples.map(([es,en])=><div className="translated-example" key={es}><b lang={lesson.locale||'es-ES'}><SpokenText text={es} lang={lesson.locale||'es-ES'}/></b><p><SpokenText text={en} lang="en-US"/></p></div>)}</section>
 </>}
 {lesson.vocabulary&&<section><span className="eyebrow">WORD → PHRASE → SENTENCE</span><h2>Your vocabulary toolkit</h2><p>Say the phrase, cover the translation, then make your own sentence.</p><div className="vocabulary-grid">{lesson.vocabulary.map(w=><article key={w.term}><h3 lang={lesson.locale||'es-ES'}><SpokenText text={w.term} lang={lesson.locale||'es-ES'}/></h3><p><SpokenText text={w.meaning} lang="en-US"/></p><strong lang={lesson.locale||'es-ES'}><SpokenText text={w.phrase} lang={lesson.locale||'es-ES'}/></strong><div className="translated-example"><b lang={lesson.locale||'es-ES'}><SpokenText text={w.example} lang={lesson.locale||'es-ES'}/></b><p><SpokenText text={w.translation} lang="en-US"/></p></div></article>)}</div>{lesson.id==='food-vocabulary'&&<p className="rule-pitfall">Agua is feminine. It takes el immediately before its stressed initial a: el agua fría. Adjectives stay feminine; the plural uses las aguas.</p>}</section>}
 </div>;
}
