import {languageInfo} from './languages.mjs';
import React,{useState,useRef} from 'react';
import {Headphones,Mic2,BookOpen,NotebookPen,Target,ChevronRight} from 'lucide-react';

const definitions=[['Reading','reading',BookOpen,'#219d8d'],['Listening','listening',Headphones,'#6172ee'],['Speaking','speaking',Mic2,'#9566da'],['Writing','writing',NotebookPen,'#dc9438'],['Language use','languageUse',Target,'#ea7957']];
const descriptions={Reading:'Understand written Spanish, from everyday messages to longer arguments.',Listening:'Follow spoken Spanish and identify the main message and relevant details.',Speaking:'Express your ideas aloud with clear meaning, intelligible speech and appropriate language.',Writing:'Write a clear response with relevant detail, suitable vocabulary and organised ideas.','Language use':'Choose grammar and vocabulary that express the intended meaning.'};
function skillEvidence(r,name,key){
 const s=r.skills?.find(s=>s.name===name);
 if(s){let band=null;for(const b of r.bands||[]){if(b[key]===undefined)break;if(b[key]<2)break;band=b.level;}
  return {level:s.level||band||(r.bands?.length?'Below A1':'—'),label:'Provisional task band',score:s.total?Math.round(s.correct/s.total*100):null,raw:`${s.correct}/${s.total}`,source:'Diagnostic questions',feedback:'Your band reflects consecutive difficulty bands meeting the test threshold. The score below retains all your answers across A1–C1.'};}
 const production=r.productions?.find(p=>p.task?.endsWith('-'+key));const result=production?.result;const a=result?.status==='reviewed'?result:result?.aiAssessment||result;
 const band=production?.task?.match(/skills-(a1|a2|b1|b2|c1)-/)?.[1]?.toUpperCase();
 const scored=Number.isFinite(a?.score);return {level:band||'—',label:band?'Task difficulty · not a proficiency rating':'Not assessed',score:scored?a.score:null,raw:scored?`${a.score}%`:'—',source:a?.status==='reviewed'?'Teacher assessment':a?.status==='ai-reviewed'?'AI assessment':a?.status==='ai-unassessable'?'Insufficient evidence':production?'Awaiting assessment':'No response yet',feedback:a?.feedback||'Submit a response and request AI assessment or a teacher review to see your score here.',next:a?.nextStep};
}
export default function LevelProfile({assessment,onOpen}){
 const [selected,setSelected]=useState('Reading');const detail=useRef(null);const r=assessment?.result;if(!r)return null;
 const entries=definitions.map(([name,key,Icon,color])=>({name,Icon,color,...skillEvidence(r,name,key)}));const active=entries.find(s=>s.name===selected)||entries[0];const accuracy=r.total?Math.round(r.correct/r.total*100):0;
 const select=name=>{setSelected(name);requestAnimationFrame(()=>{if(!detail.current)return;const header=document.querySelector('main > header');const top=window.scrollY+detail.current.getBoundingClientRect().top-(header?.getBoundingClientRect().height||0)-16;detail.current.focus({preventScroll:true});window.scrollTo({top:Math.max(0,top),behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});});};
 return <div className="level-profile"><div className="level-profile-heading"><div><span className="eyebrow">YOUR {languageInfo(r.language).name.toUpperCase()} · TEST EVIDENCE</span><h3>Current level profile</h3></div>{onOpen&&<button className="outline-button" onClick={onOpen}>Full report <ChevronRight size={16}/></button>}</div><div className="level-profile-top"><div className="level-profile-ring" style={{'--accuracy':`${accuracy*3.6}deg`}}><div><strong>{r.level}</strong><small>course placement</small></div></div><div><h3>{r.level} · your starting point</h3><p>Recommended course band from your reading and language-use test.</p><div className="level-profile-score"><b>{r.correct}/{r.total}</b><span>{accuracy}% correct · {new Date(assessment.at).toLocaleDateString()}</span></div><small>Skill scores stay separate, so you can see where to focus.</small></div></div><div className="level-profile-path" aria-label="Course placement from A1 to C1">{['A1','A2','B1','B2','C1'].map(b=><span key={b} className={b===r.level?'current':''} aria-current={b===r.level?'step':undefined}>{b}</span>)}</div><h4>Explore your skills</h4><p className="level-profile-hint">Tap a skill for its score, evidence and next step.</p><div className="level-profile-skills">{entries.map(s=><button key={s.name} type="button" aria-pressed={selected===s.name} onClick={()=>select(s.name)} style={{'--skill-color':s.color}} className={selected===s.name?'selected':''}><s.Icon size={23}/><b>{s.name}</b><strong>{s.level}</strong><small>{s.label}</small><div className="level-profile-bar"><i style={{width:`${s.score??0}%`}}/></div><span className="level-profile-raw"><b>{s.raw}</b><small>{s.source}</small></span></button>)}</div><section ref={detail} tabIndex={-1} className="level-profile-detail" style={{'--skill-color':active.color}} aria-label={`${active.name} evidence`}><div className="level-profile-detail-title"><active.Icon size={26}/><div><span className="eyebrow">{active.name}</span><h3>{active.level} <small>{active.label}</small></h3></div></div><p>{descriptions[active.name].replace('Spanish',languageInfo(r.language).name)}</p><h4>Evidence in your record</h4><p><b>{active.raw}</b> · {active.source}</p><p>{active.feedback}</p>{active.next&&<><h4>Next focus</h4><p>{active.next}</p></>}{onOpen&&<button className="outline-button" onClick={onOpen}>Results & reassessment <ChevronRight size={16}/></button>}</section><p className="level-profile-note">Provisional learning guidance, not an official CEFR qualification. Speaking and writing percentages describe performance on the displayed task band.</p></div>;
}
