import React,{useEffect,useRef,useState} from 'react';
import {Sparkles,Target,ChevronRight} from 'lucide-react';
async function request(language,method='GET'){const r=await fetch('/api/patterns?language='+language,{method,headers:{'Content-Type':'application/json'},...(method==='POST'?{body:JSON.stringify({consent:true})}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load learning patterns.');return d;}
export default function RecurringPatterns({language,user,onPractice,onNavigate}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[expanded,setExpanded]=useState(false);const live=useRef(true),tried=useRef(new Set());
 useEffect(()=>{live.current=true;if(user)request(language).then(d=>{if(live.current){setData(d);setConsent(d.enabled)}}).catch(e=>{if(live.current)setError(e.message)});return()=>{live.current=false}},[language,user?.id]);
 async function analyze(){if(busy)return;setBusy(true);setError('');try{const d=await request(language,'POST');if(live.current){setData(d);setConsent(true)}}catch(e){if(live.current)setError(e.message)}finally{if(live.current)setBusy(false)}}
 useEffect(()=>{if(data?.enabled&&data.stale&&data.available&&data.topics.length&&!tried.current.has(data.revision)){tried.current.add(data.revision);analyze()}},[data?.revision]);
 async function disable(){setConsent(false);setError('');try{await request(language,'DELETE');if(live.current)setData(d=>({...d,enabled:false,analysis:null,stale:true}))}catch(e){if(live.current){setError(e.message);setConsent(true)}}}
 const topics=data?.topics||[],items=data?.analysis?.items||[],visible=expanded?topics:topics.slice(0,4),coverage=data?.coverage;
 return <section className="panel recurring live-patterns"><div className="section-title"><div><span className="eyebrow">YOUR NEXT IMPROVEMENT</span><h2><Target size={23}/> Recurring patterns</h2></div><span className="pattern-badge">{data?.analysis?'AI + saved evidence':'Saved evidence'}</span></div>
 <p>Spot repeated difficulties, see the evidence, and choose what to practise next.</p>
 {!user?<p>Sign in to combine your saved lessons, skill assessments and class notes.</p>:<>
 {coverage&&<div className="pattern-coverage"><span>{coverage.lessons} lesson attempts</span><span>{coverage.skills} skill submissions</span><span>{coverage.assessments} level tests</span><span>{coverage.classes} class notes</span><span>{coverage.pronunciation} pronunciation attempts</span></div>}
 {!data&&!error&&<p role="status">Loading your learning evidence…</p>}
 {data&&!topics.length&&<p>No evidence yet. Complete a lesson or add a class observation to start building your patterns.</p>}
 <div className="pattern-rows">{visible.map(t=>{const ai=items.find(i=>i.topicId===t.id),lesson=ai?.lessonId||t.lessonId;return <article className="pattern-row" key={t.id}>
 <div className="pattern-row-heading"><div><span className={'pattern-status '+(t.recurring&&t.score<80?'needs-review':'')}>{t.status}</span><h3>{t.title}</h3></div><strong>{t.score===null?'—':`${t.score}%`}</strong></div>
 {t.score!==null&&<><div className="pattern-meter" role="meter" aria-label={t.title+' recent score'} aria-valuemin={0} aria-valuemax={100} aria-valuenow={t.score}><i style={{width:t.score+'%'}}/></div><small>{t.kind} · latest {Math.min(t.scoredCount,5)} scored records{t.previous!==null?` · previous five: ${t.previous}%`:''} · {t.count} records in total</small></>}
 <p>{ai?.summary||(t.score===null?'Your teacher’s observation is saved below. AI can help interpret the next step.':t.recurring&&t.score<80?`${t.lowCount} of the latest ${Math.min(t.scoredCount,5)} scored records are below 80%. Review the evidence before practising again.`:t.score>=80?'Recent results are strong. Use a new context to check that the skill transfers.':'One result is a starting point; more attempts will show whether this difficulty repeats.')}</p>
 {ai&&<div className="pattern-next"><Sparkles size={17}/><div><b>Next practice</b><p>{ai.nextStep}</p></div></div>}
 <details><summary>See evidence · {t.evidence.length} recent records</summary>{t.evidence.map(e=><div className="pattern-evidence" key={e.id}><small>{new Date(e.at).toLocaleDateString()}{e.score!==null?` · ${e.score}%`:''}{ai?.evidenceIds.includes(e.id)?' · used in AI insight':''}</small><p>{e.text}</p></div>)}</details>
 <button className="text-button" onClick={()=>lesson?onPractice(lesson):onNavigate('Learn')}>{lesson?'Practise this topic':'Explore lessons'}<ChevronRight size={16}/></button></article>})}</div>
 {topics.length>4&&<button className="outline-button" onClick={()=>setExpanded(x=>!x)}>{expanded?'Show fewer patterns':`See all ${topics.length} topics`}</button>}
 {data&&topics.length>0&&<div className="pattern-ai-controls"><b><Sparkles size={17}/> Connect your evidence with AI</b><p>All saved records in this language are counted. AI receives topic summaries and up to five recent observations per topic, including class notes and assessment feedback. No audio is sent here.</p>
 {data.available?<><label><input type="checkbox" checked={consent} onChange={e=>e.target.checked?setConsent(true):disable()}/>Allow {data.provider} to analyze this language’s learning evidence and refresh it when I return after new activity. This does not enable teacher sharing.</label><button className="primary" disabled={!consent||busy} onClick={analyze}>{busy?'Analyzing your evidence…':data.analysis?'Refresh AI insights':'Analyze with AI'}</button>{data.analysis&&<small>Updated {new Date(data.analysis.generatedAt).toLocaleString()} · {data.analysis.provider}</small>}</>:<p>AI is not connected yet. Your calculated patterns and saved evidence remain available.</p>}
 <small>Scores are calculated from saved results, not generated by AI. The 80% review threshold is a practice signal, not a CEFR level.</small></div>}
 </>}{error&&<p className="auth-error" role="alert">{error}</p>}</section>;
}
