import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Award,BookOpen,Check,CheckCircle2,ChevronRight,Clock3,Flag,Headphones,Mic2,Play,RotateCcw,Sparkles,Target,Volume2} from 'lucide-react';
import {levels,chapters,lessonList,getLesson,gradeLesson,isCorrect,summarize,validAnswer} from './course.mjs';
import './self-study.css';
async function request(route,options={}){const r=await fetch('/api'+route,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...options});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not save. Please try again.');return data;}
function readDrafts(){try{const saved=JSON.parse(localStorage.getItem('continuumLessonDrafts')||'{}');return Object.fromEntries(Object.entries(saved||{}).filter(([id,answers])=>{const lesson=getLesson(id);return lesson&&Array.isArray(answers)&&answers.length<lesson.questions.length&&answers.every((a,i)=>validAnswer(lesson.questions[i],a))}))}catch{return {}}}
function savedLevel(){try{const id=localStorage.getItem('continuumCourseLevel');return levels.some(l=>l.id===id)?id:'B1'}catch{return 'B1'}}
const iconFor=skill=>skill==='Listening'?Headphones:skill==='Speaking'||skill==='Pronunciation'?Mic2:skill==='Checkpoint'?Flag:BookOpen;
function AudioModel({text}){
 const [error,setError]=useState(''),[slow,setSlow]=useState(false);
 useEffect(()=>()=>window.speechSynthesis?.cancel(),[]);
 const play=()=>{setError('');if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){setError('Audio is unavailable in this browser. Use the transcript to practise.');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-MX';u.rate=slow?.72:.92;const voices=window.speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='es-MX')||voices.find(v=>v.lang.startsWith('es'))||null;u.onerror=()=>setError('Audio could not play. Use the transcript or try again.');window.speechSynthesis.speak(u)};
 return <div className="audio-model"><button type="button" className="primary" onClick={play}><Volume2 size={18}/>Listen / replay</button><label><input type="checkbox" checked={slow} onChange={e=>setSlow(e.target.checked)}/>Slower</label><small>Device-generated Spanish audio</small>{error&&<p role="status">{error}</p>}</div>;
}
function SpeakingPractice({prompt,model}){
 const [recording,setRecording]=useState(false),[url,setUrl]=useState(''),[error,setError]=useState('');
 const recorder=useRef(null),stream=useRef(null),clip=useRef(''),alive=useRef(true),timer=useRef(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(clip.current)URL.revokeObjectURL(clip.current)}},[]);
 const record=async()=>{setError('');if(recording){recorder.current?.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setError('Recording is unavailable here. Repeat the model aloud instead.');return}try{const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){s.getTracks().forEach(t=>t.stop());return}stream.current=s;const r=new MediaRecorder(s),chunks=[];recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onstop=()=>{clearTimeout(timer.current);s.getTracks().forEach(t=>t.stop());if(!alive.current)return;if(clip.current)URL.revokeObjectURL(clip.current);clip.current=URL.createObjectURL(new Blob(chunks,{type:r.mimeType}));setUrl(clip.current);setRecording(false)};r.start();setRecording(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop()},45000)}catch{stream.current?.getTracks().forEach(t=>t.stop());setError('Microphone access was unavailable. You can continue by practising aloud.')}};
 return <section className="speaking-practice"><span className="eyebrow">TRY IT ALOUD</span><h3>Your turn to speak</h3><p>{prompt}</p><AudioModel text={model}/><button type="button" className="outline-button" onClick={record}><Mic2 size={17}/>{recording?'Stop recording':'Record yourself (optional)'}</button>{recording&&<p role="status">Recording… up to 45 seconds</p>}{url&&<audio controls src={url}/>}<small>Your recording stays on this device for this session. Listen and compare; no automatic pronunciation score is assigned.</small>{error&&<p role="status">{error}</p>}</section>;
}
export default function SelfStudy({user,attempts,notes=[],activeLesson,onStart,onExit,onComplete}){
 const [level,setLevel]=useState(savedLevel),[progress,setProgress]=useState(()=>summarize(attempts)),[drafts,setDrafts]=useState(()=>user?{}:readDrafts()),[ready,setReady]=useState(!user),[error,setError]=useState('');
 const load=async()=>{setError('');if(!user){setProgress(summarize(attempts));setReady(true);return}try{const r=await request('/learning');setProgress(r.progress);setDrafts(Object.fromEntries(r.drafts.map(d=>[d.lesson,d.answers])));setReady(true)}catch(e){setError(e.message)}};
 useEffect(()=>{let live=true;setReady(!user);if(user){request('/learning').then(r=>{if(live){setProgress(r.progress);setDrafts(Object.fromEntries(r.drafts.map(d=>[d.lesson,d.answers])));setReady(true)}}).catch(e=>{if(live)setError(e.message)})}else{setProgress(summarize(attempts));setDrafts(readDrafts())}return()=>{live=false}},[user?.id]);
 const saveDraft=async(id,answers)=>{const next={...drafts,[id]:answers};if(user)await request('/learning/'+id,{method:'PUT',body:JSON.stringify({answers})});else localStorage.setItem('continuumLessonDrafts',JSON.stringify(next));setDrafts(next)};
 const complete=async result=>{const attempt=await onComplete(result);const next={...drafts};delete next[result.lesson];if(!user){try{localStorage.setItem('continuumLessonDrafts',JSON.stringify(next))}catch{}}setDrafts(next);setProgress(rows=>{const old=rows.find(x=>x.lesson===result.lesson);return [...rows.filter(x=>x.lesson!==result.lesson),{lesson:result.lesson,best:Math.max(old?.best||0,attempt.score),latest:attempt.score,count:(old?.count||0)+1}]});return attempt};
 const rows=Object.fromEntries(progress.map(x=>[x.lesson,x])),passed=id=>rows[id]?.best>=80;
 if(!ready)return <section className="panel"><h2>Loading your learning path…</h2>{error&&<><p role="alert">{error}</p><button className="primary" onClick={load}>Try again</button></>}</section>;
 if(activeLesson){const lesson=getLesson(activeLesson);return lesson?<LessonPlayer key={activeLesson} lesson={lesson} initialAnswers={drafts[activeLesson]} onDraft={answers=>saveDraft(activeLesson,answers)} onComplete={complete} onExit={onExit}/>:<section className="panel"><h2>Lesson not found</h2><button className="primary" onClick={onExit}>Back to learning path</button></section>}
 const selected=levels.find(x=>x.id===level),all=lessonList.filter(l=>l.level===level),done=all.filter(l=>passed(l.id)).length,totalDone=lessonList.filter(l=>passed(l.id)).length;
 const currentDraft=all.find(l=>Array.isArray(drafts[l.id]));
 const nextLesson=currentDraft||all.find(l=>!passed(l.id))||all[0];
 const recommended=notes[0]?.focus?.toLowerCase().includes('por')?getLesson('porpara'):getLesson('subjunctive');
 return <div className="study-page"><div className="study-intro"><div><span className="eyebrow">YOUR SPANISH JOURNEY</span><h1>A little practice. A bigger world.</h1><p>Explore the whole path, choose a chapter and keep moving.</p></div><div className="study-total"><Award size={22}/><b>{totalDone}<small> / {lessonList.length}</small></b><span>lessons mastered</span></div></div>
 <section className="study-hero"><div><span className="pill"><Sparkles size={15}/>{currentDraft?'PICK UP WHERE YOU LEFT OFF':'YOUR NEXT STEP'}</span><h2>{nextLesson.title}</h2><p>{chapters.find(c=>c.id===nextLesson.chapter)?.goal}</p><div className="study-meta"><span>{level} · {nextLesson.skill}</span><span><Clock3 size={15}/>{nextLesson.minutes} min</span>{rows[nextLesson.id]&&<span>Last score {rows[nextLesson.id].latest}%</span>}</div><button className="primary" onClick={()=>onStart(nextLesson.id)}>{currentDraft?'Resume lesson':passed(nextLesson.id)?'Review lesson':'Start lesson'}<ArrowRight size={18}/></button></div><div className="journey-ring" style={{'--progress':`${done/all.length*360}deg`}}><div><b>{done}/{all.length}</b><span>{level} lessons</span></div></div></section>
 <div className="study-level-heading"><h2>Your course roadmap</h2><span>20 lessons + 10 checkpoints</span></div><div className="level-roadmap" role="group" aria-label="Choose course level">{levels.map((l,i)=>{const items=lessonList.filter(x=>x.level===l.id),count=items.filter(x=>passed(x.id)).length;return <button key={l.id} className={level===l.id?'active':''} onClick={()=>{setLevel(l.id);try{localStorage.setItem('continuumCourseLevel',l.id)}catch{}}} aria-pressed={level===l.id}><span className="level-number">{i+1}</span><strong>{l.id}</strong><span>{l.name}</span><small>{count}/{items.length} mastered</small><i><em style={{width:`${count/items.length*100}%`}}/></i></button>})}</div>
 <p className="roadmap-note">A compact course across A1–C1 difficulty levels. Master a lesson with 80% or more. These course milestones do not certify a CEFR level. You can explore any level.</p>
 <div className="study-columns"><div><div className="chapter-heading"><span className="eyebrow">{level} · {selected.name}</span><h2>{selected.description}</h2></div>{chapters.filter(c=>c.level===level).map((c,i)=>{const units=lessonList.filter(l=>l.chapter===c.id);return <section className="study-chapter" key={c.id}><div className="chapter-top"><span className="chapter-badge">{String(i+1).padStart(2,'0')}</span><div><span className="eyebrow">CHAPTER {i+1}</span><h3>{c.title}</h3><p>{c.goal}</p></div><small>{units.filter(l=>passed(l.id)).length}/{units.length}</small></div><div className="lesson-trail">{units.map(l=>{const Icon=iconFor(l.skill),row=rows[l.id],started=Array.isArray(drafts[l.id]),mastered=passed(l.id);return <button key={l.id} className={`trail-lesson ${mastered?'mastered':''} ${l.checkpoint?'checkpoint':''}`} onClick={()=>onStart(l.id)}><span className="trail-node">{mastered?<Check size={22}/>:<Icon size={22}/>}</span><div><span className="eyebrow">{l.skill} · {l.minutes} MIN</span><h4>{l.title}</h4><p>{started?`In progress · ${drafts[l.id].length}/${l.questions.length} questions`:row?`Latest ${row.latest}% · Best ${row.best}%${mastered?' · Mastered':' · Review recommended'}`:l.checkpoint?'Put this chapter into practice':'Explanation + guided practice'}</p></div><span className="trail-action">{started?'Resume':row?'Review':'Start'}<ChevronRight size={16}/></span></button>})}</div></section>})}</div>
 <aside className="study-aside"><section className="panel"><span className="eyebrow">FROM CLASS TO PRACTICE</span><Sparkles size={23}/><h3>{notes.length?'Keep your class momentum':'A focus for today'}</h3><p>{notes.length?`Latest class focus: ${notes[0].focus}.`:'Revisit doubt, purpose and uncertainty in a short focused lesson.'}</p>{notes[0]&&<blockquote>{notes[0].note}</blockquote>}<button className="outline-button" onClick={()=>onStart(recommended.id)}>{recommended.title}<ChevronRight size={16}/></button></section><section className="panel"><span className="eyebrow">HOW YOUR PATH WORKS</span><h3>Learn. Try. Remember.</h3><ol><li>Read a short explanation and example.</li><li>Practise with immediate feedback.</li><li>Review mistakes and revisit a checkpoint.</li></ol><p>{user?'Your scores and lesson position are saved to your account. Teacher visibility follows your sharing setting in Account.':'Preview progress is saved on this device. Sign in to keep future lessons across devices.'}</p></section></aside></div></div>;
}
function LessonPlayer({lesson,initialAnswers,onDraft,onComplete,onExit}){
 const restored=Array.isArray(initialAnswers)?initialAnswers:[];
 const [phase,setPhase]=useState(initialAnswers?'exercise':'intro'),[answers,setAnswers]=useState(restored),[choice,setChoice]=useState(null),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[submission,setSubmission]=useState(()=>crypto.randomUUID());
 const q=lesson.questions[answers.length],good=q&&choice!==null&&isCorrect(q,choice);
 const start=async()=>{if(busy)return;setBusy(true);setError('');try{await onDraft([]);setAnswers([]);setChoice(null);setChecked(false);setSubmission(crypto.randomUUID());setPhase('exercise')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const next=async()=>{if(busy||!checked)return;const full=[...answers,choice];setBusy(true);setError('');try{if(full.length===lesson.questions.length){const grade=gradeLesson(lesson.id,full);const saved=await onComplete({...grade,lesson:lesson.id,answers:full,at:new Date().toISOString(),submissionKey:submission});setAnswers(full);setResult(saved);setPhase('result')}else{await onDraft(full);setAnswers(full);setChoice(null);setChecked(false)}}catch(e){setError(e.message)}finally{setBusy(false)}};
 const errorBox=error&&<p className="auth-error" role="alert">{error} Your current answer is still here. Try again.</p>;
 if(phase==='intro')return <div className="study-lesson"><button className="back" onClick={onExit}><ArrowLeft size={17}/>Back to learning path</button><section className="lesson-intro-card"><span className="eyebrow">{lesson.level} · {lesson.skill} · {lesson.minutes} MIN</span><h1>{lesson.title}</h1><p>{lesson.explanation}</p><div className="lesson-example"><span className="eyebrow">EXAMPLE</span><p lang="es">{lesson.example}</p></div>{lesson.speak&&<SpeakingPractice prompt={lesson.speak} model={lesson.example}/>}<div className="lesson-begin"><span>{lesson.questions.length} questions · feedback after every answer</span><button className="primary" disabled={busy} onClick={start}>{busy?'Saving…':'Start practice'}<ArrowRight size={17}/></button></div>{errorBox}</section></div>;
 if(phase==='result'){const missed=lesson.questions.map((q,i)=>({q,a:answers[i],i})).filter(x=>!isCorrect(x.q,x.a));return <div className="study-lesson"><section className="result-card"><div className="result-icon"><Award size={38}/></div><span className="eyebrow">{result.score>=80?'LESSON MASTERED':'PRACTICE SAVED'}</span><h1>{result.score}% accuracy</h1><h2>{lesson.title}</h2><p>{lesson.skill==='Pronunciation'?'This score checks word-stress knowledge.':'Your exercise result is saved.'} {result.score>=80?'Your course milestone is complete.':'Review the explanations, then try for 80%.'}</p><button className="primary" onClick={onExit}>See updated learning path<ArrowRight size={17}/></button><button className="text-button" disabled={busy} onClick={start}><RotateCcw size={16}/>Try again</button>{errorBox}</section>{missed.length>0&&<section className="panel mistake-review"><span className="eyebrow">A LITTLE REVIEW GOES A LONG WAY</span><h2>What to revisit</h2>{missed.map(({q,a,i})=><article key={i}><b>{q.prompt}</b><p>Your answer: {q.type==='text'?a:q.options[a]}</p><p>Correct answer: {q.type==='text'?q.answer:q.options[q.answer]}</p><small>{q.note}</small></article>)}</section>}</div>}
 return <div className="study-lesson"><div className="practice-top"><button className="back" disabled={busy} onClick={onExit}><ArrowLeft size={17}/>Save & exit</button><div className="practice-progress"><i style={{width:`${answers.length/lesson.questions.length*100}%`}}/></div><span>{answers.length+1}/{lesson.questions.length}</span></div><div className="lesson-context"><b>{lesson.title}</b><span>{lesson.level} · {lesson.skill}</span></div><section className="question-card" key={answers.length}><span className="eyebrow">{q.audio?'LISTEN AND RESPOND':q.type==='text'?'WRITE THE MISSING WORD':'CHOOSE YOUR ANSWER'}</span>{q.audio&&<><AudioModel text={q.audio}/><details className="audio-transcript"><summary>Show transcript</summary><p lang="es">{q.audio}</p></details></>}<h1>{q.prompt}</h1>{q.type==='text'?<form onSubmit={e=>{e.preventDefault();if(!checked&&String(choice||'').trim())setChecked(true)}}><label htmlFor="written-answer">Your answer</label><input id="written-answer" className="written-answer" autoComplete="off" value={choice??''} onChange={e=>setChoice(e.target.value)} maxLength={150} disabled={checked} /></form>:<div className="answers">{q.options.map((o,i)=><button key={i} disabled={checked} aria-pressed={choice===i} onClick={()=>setChoice(i)} className={`${choice===i?'selected':''} ${checked&&i===q.answer?'correct':''} ${checked&&choice===i&&i!==q.answer?'wrong':''}`}><span>{String.fromCharCode(65+i)}</span>{o}{checked&&i===q.answer&&<CheckCircle2 size={19}/>}</button>)}</div>}{checked&&<div className={`feedback ${good?'good':'retry'}`} role="status"><b>{good?'That’s right.':'Let’s take another look.'}</b><p>{q.note}</p></div>}{errorBox}<button className="primary wide" disabled={busy||choice===null||(q.type==='text'&&!String(choice).trim())} onClick={checked?next:()=>setChecked(true)}>{busy?'Saving…':checked?(answers.length===lesson.questions.length-1?'Finish & save':'Continue'):'Check answer'}<ChevronRight size={17}/></button><small className="save-hint">Progress saves after Continue. The current question can be repeated when you return.</small></section><details className="lesson-help"><summary>Review the lesson explanation</summary><p>{lesson.explanation}</p><p lang="es">{lesson.example}</p></details></div>;
}
