import {languageInfo} from './languages.mjs';
import SentenceAudio,{SpokenText} from './SentenceAudio.jsx';
import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Award,BookOpen,Check,CheckCircle2,ChevronRight,Clock3,Flag,Headphones,Mic2,Play,RotateCcw,Sparkles,Target,Volume2} from 'lucide-react';
import {levels,chapters as allChapters,lessonList as allLessons,getLesson,getLessonVariant,gradeLesson,isCorrect,summarize,validAnswer} from './course.mjs';
import {scorePronunciation} from './pronunciation-score.mjs';
import './self-study.css';
import SkillsWorkshop from './SkillsWorkshop.jsx';
import LessonReference from './LessonReference.jsx';
async function request(route,options={}){const r=await fetch('/api'+route,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...options});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not save. Please try again.');return data;}
function readSeeds(){try{return JSON.parse(localStorage.getItem('continuumTestSeeds')||'{}')}catch{return {}}}
function readDrafts(){try{const saved=JSON.parse(localStorage.getItem('continuumLessonDrafts')||'{}');return Object.fromEntries(Object.entries(saved||{}).filter(([id,answers])=>{const lesson=getLessonVariant(id,readSeeds()[id]);return lesson&&Array.isArray(answers)&&answers.length<lesson.questions.length&&answers.every((a,i)=>validAnswer(lesson.questions[i],a))}))}catch{return {}}}
function savedLevel(language='es'){try{const id=localStorage.getItem('continuumCourseLevel'+(language==='es'?'':':'+language));return levels.some(l=>l.id===id)?id:(language==='es'?'B1':'A1')}catch{return language==='es'?'B1':'A1'}}
const iconFor=skill=>skill==='Listening'?Headphones:skill==='Speaking'||skill==='Pronunciation'?Mic2:skill==='Checkpoint'?Flag:BookOpen;
function AudioModel({text,locale='es-ES'}){return <SentenceAudio text={text} lang={locale}/>;}
function SpeakingPractice({prompt,model,target,lessonId,user,locale='es-ES'}){
 const [recording,setRecording]=useState(false),[url,setUrl]=useState(''),[error,setError]=useState(''),[heard,setHeard]=useState(''),[result,setResult]=useState(null),[checking,setChecking]=useState(false);
 const recorder=useRef(null),recognition=useRef(null),stream=useRef(null),clip=useRef(''),alive=useRef(true),timer=useRef(null),transcript=useRef(''),started=useRef(0);
 const supported=typeof window!=='undefined'&&!!(window.SpeechRecognition||window.webkitSpeechRecognition);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();try{recognition.current?.abort()}catch{}stream.current?.getTracks().forEach(t=>t.stop());if(clip.current)URL.revokeObjectURL(clip.current)}},[]);
 const assess=async durationMs=>{const spoken=transcript.current.trim();if(!spoken){setChecking(false);setError(supported?'No speech was recognized. Try again closer to the microphone.':'Automatic matching is unavailable in this browser. You can still replay your recording.');return}const scored={...scorePronunciation(target,spoken),heard:spoken,saved:!user};setHeard(spoken);setResult(scored);setChecking(!!user);if(!user)return;try{await request('/pronunciation',{method:'POST',body:JSON.stringify({lesson:lessonId,targetVersion:lessonId+'-model-v1',score:scored.score,durationMs:Math.max(250,Math.min(120000,durationMs)),submissionKey:crypto.randomUUID()})});if(alive.current)setResult(x=>x&&({...x,saved:true}))}catch(e){if(alive.current)setError('Your match was calculated, but could not be saved: '+e.message)}finally{if(alive.current)setChecking(false)}};
 const stop=()=>{clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();try{recognition.current?.stop()}catch{}};
 const record=async()=>{setError('');if(recording){stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setError('Recording is unavailable here. Repeat the model aloud instead.');return}setResult(null);setHeard('');transcript.current='';try{const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){s.getTracks().forEach(t=>t.stop());return}stream.current=s;const r=new MediaRecorder(s),chunks=[];recorder.current=r;started.current=Date.now();
  if(supported){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition,recognizer=new Recognition();recognition.current=recognizer;recognizer.lang=locale;recognizer.continuous=true;recognizer.interimResults=true;recognizer.maxAlternatives=1;recognizer.onresult=e=>{let final='',interim='';for(let i=0;i<e.results.length;i++){const words=e.results[i][0]?.transcript||'';if(e.results[i].isFinal)final+=' '+words;else interim+=' '+words}transcript.current=(final+' '+interim).trim();if(alive.current)setHeard(transcript.current)};recognizer.onerror=e=>{if(e.error!=='aborted'&&e.error!=='no-speech'&&alive.current)setError('Speech matching was interrupted. Your recording can still be replayed.')};try{recognizer.start()}catch{recognition.current=null}}
  r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onstop=()=>{clearTimeout(timer.current);try{recognition.current?.stop()}catch{}s.getTracks().forEach(t=>t.stop());if(!alive.current)return;if(clip.current)URL.revokeObjectURL(clip.current);clip.current=URL.createObjectURL(new Blob(chunks,{type:r.mimeType}));setUrl(clip.current);setRecording(false);if(supported&&recognition.current){setChecking(true);setTimeout(()=>alive.current&&assess(Date.now()-started.current),650)}else setError('Automatic matching is unavailable in this browser. You can still replay and compare your recording.')};r.start();setRecording(true);timer.current=setTimeout(stop,30000)
 }catch{stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);setError('Microphone access was unavailable. You can continue by practising aloud.')}};
 return <section className="speaking-practice"><span className="eyebrow">SPEAK & CHECK</span><h3>Your turn to speak</h3><p>{prompt}</p><div className="pronunciation-target"><span>Repeat this model for instant feedback</span><b lang={locale}>{target}</b></div><AudioModel text={target||model} locale={locale}/><button type="button" className="outline-button" disabled={checking} onClick={record}><Mic2 size={17}/>{recording?'Stop & assess':checking?'Checking…':'Record & assess (optional)'}</button>{recording&&<p role="status">Recording and listening… up to 30 seconds</p>}{url&&<audio controls src={url}/>} {heard&&<p className="heard-words"><b>Browser heard:</b> <span lang="es">{heard}</span> <small>Session only — not saved</small></p>}{result&&<div className="pronunciation-result" role="status"><div className="match-score"><b>{result.score}%</b><span>speech match</span></div><div><h4>{result.label}</h4><p>{result.missing.length?`Try these words again: ${result.missing.join(', ')}.`:'Every model word was recognized in sequence.'}</p><small>{result.saved?(user?'Saved to your learning record.':'Available for this session.'):'Saving result…'}</small></div></div>}<small>Your audio stays in this browser session and is never uploaded to Continuum. Speech recognition may be processed by your browser or its provider. Only the match score, lesson and duration are saved when signed in; teacher visibility follows your Account sharing setting. This is a speech-recognition match—not a phoneme, accent or CEFR assessment.</small>{error&&<p className="pronunciation-warning" role="status">{error}</p>}</section>;
}
export default function SelfStudy({language='es',user,attempts,notes=[],activeLesson,onStart,onExit,onComplete}){
 const lessonList=allLessons.filter(l=>(l.language||'es')===language),chapters=allChapters.filter(c=>(c.language||'es')===language&&!c.legacy),lang=languageInfo(language);
 const [level,setLevel]=useState(()=>savedLevel(language)),[progress,setProgress]=useState(()=>summarize(attempts)),[drafts,setDrafts]=useState(()=>user?{}:readDrafts()),[draftSeeds,setDraftSeeds]=useState(()=>user?{}:readSeeds()),[ready,setReady]=useState(!user),[error,setError]=useState('');
 const load=async()=>{setError('');if(!user){setProgress(summarize(attempts));setReady(true);return}try{const r=await request('/learning');setProgress(r.progress);setDrafts(Object.fromEntries(r.drafts.map(d=>[d.lesson,d.answers])));setDraftSeeds(Object.fromEntries(r.drafts.map(d=>[d.lesson,d.seed])));setReady(true)}catch(e){setError(e.message)}};
 useEffect(()=>{let live=true;setReady(!user);if(user){request('/learning').then(r=>{if(live){setProgress(r.progress);setDrafts(Object.fromEntries(r.drafts.map(d=>[d.lesson,d.answers])));setDraftSeeds(Object.fromEntries(r.drafts.map(d=>[d.lesson,d.seed])));setReady(true)}}).catch(e=>{if(live)setError(e.message)})}else{setProgress(summarize(attempts));setDrafts(readDrafts());setDraftSeeds(readSeeds())}return()=>{live=false}},[user?.id]);
 const saveDraft=async(id,answers,seed)=>{const next={...drafts,[id]:answers},seeds={...draftSeeds,[id]:seed};if(user)await request('/learning/'+id,{method:'PUT',body:JSON.stringify({answers,seed})});else{localStorage.setItem('continuumTestSeeds',JSON.stringify(seeds));localStorage.setItem('continuumLessonDrafts',JSON.stringify(next))}setDrafts(next);setDraftSeeds(seeds)};
 const complete=async result=>{const attempt=await onComplete(result);const next={...drafts};delete next[result.lesson];if(!user){try{localStorage.setItem('continuumLessonDrafts',JSON.stringify(next))}catch{}}setDrafts(next);setProgress(rows=>{const old=rows.find(x=>x.lesson===result.lesson);return [...rows.filter(x=>x.lesson!==result.lesson),{lesson:result.lesson,best:Math.max(old?.best||0,attempt.score),latest:attempt.score,count:(old?.count||0)+1}]});return attempt};
 const rows=Object.fromEntries(progress.map(x=>[x.lesson,x])),passed=id=>rows[id]?.best>=(getLesson(id)?.passScore||80);
 if(!ready)return <section className="panel"><h2>Loading your learning path…</h2>{error&&<><p role="alert">{error}</p><button className="primary" onClick={load}>Try again</button></>}</section>;
 if(activeLesson){const lesson=getLesson(activeLesson);return lesson?<LessonPlayer key={activeLesson} lesson={lesson} language={language} user={user} initialAnswers={drafts[activeLesson]} initialSeed={draftSeeds[activeLesson]} onDraft={(answers,seed)=>saveDraft(activeLesson,answers,seed)} onComplete={complete} onExit={onExit}/>:<section className="panel"><h2>Lesson not found</h2><button className="primary" onClick={onExit}>Back to learning path</button></section>}
 const selected={...levels.find(x=>x.id===level),description:language==='es'?levels.find(x=>x.id===level).description:`Build your ${lang.name} communication skills at ${level}.`},all=lessonList.filter(l=>l.level===level),done=all.filter(l=>passed(l.id)).length,totalDone=lessonList.filter(l=>passed(l.id)).length;
 const currentDraft=all.find(l=>Array.isArray(drafts[l.id]));
 const nextLesson=currentDraft||all.find(l=>!passed(l.id))||all[0];
 const recommended=language!=='es'?(all.find(l=>!l.checkpoint&&!l.summaryTest&&!passed(l.id))||all[0]):notes[0]?.focus?.toLowerCase().includes('por')?getLesson('porpara'):getLesson('subjunctive');
 return <div className="study-page"><div className="study-intro"><div><span className="eyebrow">YOUR {lang.name.toUpperCase()} JOURNEY</span><h1>A little practice. A bigger world.</h1><p>Explore the whole path, choose a chapter and keep moving.</p></div><div className="study-total"><Award size={22}/><b>{totalDone}<small> / {lessonList.length}</small></b><span>lessons mastered</span></div></div>
 <section className="study-hero"><div><span className="pill"><Sparkles size={15}/>{currentDraft?'PICK UP WHERE YOU LEFT OFF':'YOUR NEXT STEP'}</span><h2>{nextLesson.title}</h2><p>{chapters.find(c=>c.id===nextLesson.chapter)?.goal}</p><div className="study-meta"><span>{level} · {nextLesson.skill}</span><span><Clock3 size={15}/>{nextLesson.minutes} min</span>{rows[nextLesson.id]&&<span>Last score {rows[nextLesson.id].latest}%</span>}</div><button className="primary" onClick={()=>onStart(nextLesson.id)}>{currentDraft?'Resume lesson':passed(nextLesson.id)?'Review lesson':'Start lesson'}<ArrowRight size={18}/></button></div><div className="journey-ring" style={{'--progress':`${done/all.length*360}deg`}}><div><b>{done}/{all.length}</b><span>{level} lessons</span></div></div></section>
 <div className="study-level-heading"><h2>Your course roadmap</h2><span>{lessonList.filter(l=>!l.checkpoint&&!l.summaryTest).length} lessons · {lessonList.filter(l=>l.checkpoint).length} checkpoints · {lessonList.filter(l=>l.summaryTest).length} level reviews</span></div><div className="level-roadmap" role="group" aria-label="Choose course level">{levels.map((l,i)=>{const items=lessonList.filter(x=>x.level===l.id),count=items.filter(x=>passed(x.id)).length;return <button key={l.id} className={level===l.id?'active':''} onClick={()=>{setLevel(l.id);try{localStorage.setItem('continuumCourseLevel'+(language==='es'?'':':'+language),l.id)}catch{}}} aria-pressed={level===l.id}><span className="level-number">{i+1}</span><strong>{l.id}</strong><span>{l.name}</span><small>{count}/{items.length} mastered</small><i><em style={{width:`${count/items.length*100}%`}}/></i></button>})}</div>
 <p className="roadmap-note">Explore grammar labs with conjugation tables and vocabulary labs alongside communication lessons, across A1–C1 course difficulty levels. Master a lesson with 80% or more. These course milestones do not certify a CEFR level. You can explore any level.</p>
 <SkillsWorkshop language={language} level={level} user={user}/><div className="study-columns"><div><div className="chapter-heading"><span className="eyebrow">{level} · {selected.name}</span><h2>{selected.description}</h2></div>{chapters.filter(c=>c.level===level).map((c,i)=>{const units=lessonList.filter(l=>l.chapter===c.id);return <section className="study-chapter" key={c.id}><div className="chapter-top"><span className="chapter-badge">{String(i+1).padStart(2,'0')}</span><div><span className="eyebrow">CHAPTER {i+1}{c.kind?` · ${c.kind.toUpperCase()}`: ''}</span><h3>{c.title}</h3><p>{c.goal}</p></div><small>{units.filter(l=>passed(l.id)).length}/{units.length}</small></div><div className="lesson-trail">{units.map(l=>{const Icon=iconFor(l.skill),row=rows[l.id],started=Array.isArray(drafts[l.id]),mastered=passed(l.id);return <button key={l.id} className={`trail-lesson ${mastered?'mastered':''} ${l.checkpoint?'checkpoint':''}`} onClick={()=>onStart(l.id)}><span className="trail-node">{mastered?<Check size={22}/>:<Icon size={22}/>}</span><div><span className="eyebrow">{l.skill} · {l.minutes} MIN</span><h4>{l.title}</h4><p>{started?`In progress · ${drafts[l.id].length}/${getLessonVariant(l.id,draftSeeds[l.id]).questions.length} questions`:row?`Latest ${row.latest}% · Best ${row.best}%${mastered?' · Mastered':' · Review recommended'}`:l.checkpoint||l.summaryTest?'New situations · mixed questions':'Explanation + guided practice'}</p></div><span className="trail-action">{started?'Resume':row?'Review':'Start'}<ChevronRight size={16}/></span></button>})}</div></section>})}</div>
 <aside className="study-aside"><section className="panel"><span className="eyebrow">FROM CLASS TO PRACTICE</span><Sparkles size={23}/><h3>{notes.length?'Keep your class momentum':'A focus for today'}</h3><p>{notes.length?`Latest class focus: ${notes[0].focus}.`:'Choose a short lesson and practise using it in a new situation.'}</p>{notes[0]&&<blockquote>{notes[0].note}</blockquote>}<button className="outline-button" onClick={()=>onStart(recommended.id)}>{recommended.title}<ChevronRight size={16}/></button></section><section className="panel"><span className="eyebrow">HOW YOUR PATH WORKS</span><h3>Learn. Try. Remember.</h3><ol><li>Read a short explanation and example.</li><li>Practise with immediate feedback.</li><li>Review mistakes and revisit a checkpoint.</li></ol><p>{user?'Your scores and lesson position are saved to your account. Teacher visibility follows your sharing setting in Account.':'Preview progress is saved on this device. Sign in to keep future lessons across devices.'}</p></section></aside></div></div>;
}
function LessonPlayer({lesson:baseLesson,language='es',user,initialAnswers,initialSeed,onDraft,onComplete,onExit}){
 const [seed,setSeed]=useState(initialSeed);const lesson=getLessonVariant(baseLesson.id,seed);
 const restored=Array.isArray(initialAnswers)?initialAnswers:[];
 const [phase,setPhase]=useState(initialAnswers?'exercise':'intro'),[answers,setAnswers]=useState(restored),[choice,setChoice]=useState(null),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[submission,setSubmission]=useState(()=>crypto.randomUUID());
 // Reset after the new screen is committed, not while the old roadmap is
 // still mounted. Instant scrolling also cancels the parent's smooth scroll.
 // Recheck on the next frame for mobile layout/scroll anchoring, and cancel
 // that callback when leaving. Answer selection/feedback must not reset scroll.
 useLayoutEffect(()=>{
  const reset=()=>window.scrollTo({top:0,left:0,behavior:'instant'});
  reset();
  const frame=requestAnimationFrame(reset);
  return()=>cancelAnimationFrame(frame);
 },[lesson.id,phase,answers.length]);
 const q=lesson.questions[answers.length],good=q&&choice!==null&&isCorrect(q,choice);
 const start=async()=>{if(busy)return;setBusy(true);setError('');try{const nextSeed=baseLesson.checkpoint||baseLesson.summaryTest?'v1-'+crypto.randomUUID():undefined;await onDraft([],nextSeed);setSeed(nextSeed);setAnswers([]);setChoice(null);setChecked(false);setSubmission(crypto.randomUUID());setPhase('exercise')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const next=async()=>{if(busy||!checked)return;const full=[...answers,choice];setBusy(true);setError('');try{if(full.length===lesson.questions.length){const grade=gradeLesson(lesson.id,full,seed);const saved=await onComplete({...grade,lesson:lesson.id,answers:full,seed,at:new Date().toISOString(),submissionKey:submission});setAnswers(full);setResult(saved);setPhase('result')}else{await onDraft(full,seed);setAnswers(full);setChoice(null);setChecked(false)}}catch(e){setError(e.message)}finally{setBusy(false)}};
 const errorBox=error&&<p className="auth-error" role="alert">{error} Your current answer is still here. Try again.</p>;
 if(phase==='intro')return <div className="study-lesson"><button className="back" onClick={onExit}><ArrowLeft size={17}/>Back to learning path</button><section className="lesson-intro-card"><span className="eyebrow">{lesson.level} · {lesson.skill} · {lesson.minutes} MIN</span><h1>{lesson.title}</h1><p>{baseLesson.checkpoint||baseLesson.summaryTest?"Apply what you learned in new situations. Questions and choices vary between attempts; your selected questions are saved when you start.":<SpokenText text={lesson.explanation}/>}</p><div className="lesson-example"><span className="eyebrow">EXAMPLE</span><p lang="es"><SpokenText text={lesson.example} lang={lesson.exampleLang||lesson.locale||'auto'}/></p></div><LessonReference lesson={lesson}/>{lesson.speak&&<SpeakingPractice prompt={lesson.speak} model={lesson.example} target={lesson.pronunciationTarget||lesson.example} lessonId={lesson.id} user={user} locale={lesson.locale||languageInfo(language).locale}/>}<div className="lesson-begin"><span>{baseLesson.summaryTest?allChapters.filter(c=>c.level===baseLesson.level&&(c.language||'es')===(baseLesson.language||'es')&&!c.summaryTest).length*(baseLesson.language?7:3):lesson.questions.length} questions · feedback after every answer</span><button className="primary" disabled={busy} onClick={start}>{busy?'Saving…':'Start practice'}<ArrowRight size={17}/></button></div>{errorBox}</section></div>;
 if(phase==='result'){const missed=lesson.questions.map((q,i)=>({q,a:answers[i],i})).filter(x=>!isCorrect(x.q,x.a));const threshold=lesson.passScore||80,passedTest=result.score>=threshold;return <div className="study-lesson"><section className={`result-card ${lesson.summaryTest?'level-result':''}`}><div className="result-icon"><Award size={38}/></div><span className="eyebrow">{lesson.summaryTest?(passedTest?'LEVEL COMPLETED':'LEVEL REVIEW SAVED'):(result.score>=threshold?'LESSON MASTERED':'PRACTICE SAVED')}</span><h1>{result.score}% accuracy</h1><h2>{lesson.title}</h2><p>{lesson.summaryTest?(passedTest?`You reached the ${threshold}% pass mark. You are recommended to continue to the next level.`:`You need ${threshold}% to pass this level review. Revisit the roadmap and try again.`):lesson.skill==='Pronunciation'?'This score checks word-stress knowledge.':'Your exercise result is saved.'} {!lesson.summaryTest&& (result.score>=threshold?'Your course milestone is complete.':'Review the explanations, then try for 80%.')}</p>{lesson.summaryTest&&passedTest&&<div className="level-certificate"><Award size={20}/><div><b>{lesson.level} pathway completed</b><small>Completion recommendation issued · {new Date().toLocaleDateString()}</small></div></div>}<button className="primary" onClick={onExit}>See updated learning path<ArrowRight size={17}/></button><button className="text-button" disabled={busy} onClick={start}><RotateCcw size={16}/>Try again</button>{errorBox}</section>{missed.length>0&&<section className="panel mistake-review"><span className="eyebrow">A LITTLE REVIEW GOES A LONG WAY</span><h2>What to revisit</h2>{missed.map(({q,a,i})=><article key={i}><b>{q.prompt}</b><p>Your answer: {q.type==='text'?a:q.options[a]}</p><p>Correct answer: {q.type==='text'?q.answer:q.options[q.answer]}</p><small>{q.note}</small></article>)}</section>}</div>}
 return <div className="study-lesson"><div className="practice-top"><button className="back" disabled={busy} onClick={onExit}><ArrowLeft size={17}/>Save & exit</button><div className="practice-progress"><i style={{width:`${answers.length/lesson.questions.length*100}%`}}/></div><span>{answers.length+1}/{lesson.questions.length}</span></div><div className="lesson-context"><b>{lesson.title}</b><span>{lesson.level} · {lesson.skill}</span></div><section className="question-card" key={answers.length}><span className="eyebrow">{q.audio?'LISTEN AND RESPOND':q.type==='text'?'WRITE THE MISSING WORD':'CHOOSE YOUR ANSWER'}</span>{q.audio&&<><AudioModel text={q.audioSpeech||q.audio}/><details className="audio-transcript"><summary>Show transcript</summary><p lang="es">{q.audio}</p></details></>}<h1>{q.prompt}</h1><SentenceAudio text={q.prompt} lang={q.promptLang||'auto'}/>{q.type==='text'?<form onSubmit={e=>{e.preventDefault();if(!checked&&String(choice||'').trim())setChecked(true)}}><label htmlFor="written-answer">Your answer</label><input id="written-answer" className="written-answer" autoComplete="off" value={choice??''} onChange={e=>setChoice(e.target.value)} maxLength={150} disabled={checked} /></form>:<div className="answers">{q.options.map((o,i)=><div className="answer-with-audio" key={i}><button disabled={checked} aria-pressed={choice===i} onClick={()=>setChoice(i)} className={`${choice===i?'selected':''} ${checked&&i===q.answer?'correct':''} ${checked&&choice===i&&i!==q.answer?'wrong':''}`}><span>{String.fromCharCode(65+i)}</span>{o}{checked&&i===q.answer&&<CheckCircle2 size={19}/>}</button><SentenceAudio text={o} lang={q.optionsLang||'auto'} compact/></div>)}</div>}{checked&&<div className={`feedback ${good?'good':'retry'}`} role="status"><b>{good?'That’s right.':'Let’s take another look.'}</b><p><SpokenText text={q.note}/></p></div>}{errorBox}<button className="primary wide" disabled={busy||choice===null||(q.type==='text'&&!String(choice).trim())} onClick={checked?next:()=>setChecked(true)}>{busy?'Saving…':checked?(answers.length===lesson.questions.length-1?'Finish & save':'Continue'):'Check answer'}<ChevronRight size={17}/></button><small className="save-hint">Progress saves after Continue. The current question can be repeated when you return.</small></section><details className="lesson-help"><summary>Review the lesson explanation</summary><p><SpokenText text={lesson.explanation}/></p><p lang="es"><SpokenText text={lesson.example} lang={lesson.exampleLang||lesson.locale||'auto'}/></p><LessonReference lesson={lesson}/></details></div>;
}
