import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {skillTasks,getSkillTask,rubricFor,rubricAnchors} from './skills-content.mjs';
import './skills-workshop.css';
export async function skillRequest(path='',method='GET',body){const r=await fetch('/api/skills'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to save your response');return d;}
export function ListeningAudio({text,test=false,onPlayed}){
 const [error,setError]=useState(''),[slow,setSlow]=useState(false),[playing,setPlaying]=useState(false);
 useEffect(()=>()=>window.speechSynthesis?.cancel(),[text]);
 const play=()=>{setError('');const synth=window.speechSynthesis;if(!synth||!window.SpeechSynthesisUtterance){setError('Audio playback is unavailable. Try Safari or Chrome with Spanish speech enabled.');return;}synth.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-ES';u.voice=synth.getVoices().find(v=>v.lang.startsWith('es'))||null;u.rate=slow?.75:.95;u.onstart=()=>{setPlaying(true);onPlayed?.()};u.onend=()=>setPlaying(false);u.onerror=e=>{setPlaying(false);if(e.error!=='canceled'&&e.error!=='interrupted')setError('Audio could not play. Check your device voice settings and try again.');};synth.speak(u);};
 return <div className="skills-audio"><button type="button" className="primary" onClick={play}>{playing?'Replay audio':'Listen / replay'}</button>{!test&&<label><input type="checkbox" checked={slow} onChange={e=>setSlow(e.target.checked)}/>Slower</label>}<small>Device-generated Spanish audio{test?' · transcript hidden during the test':''}</small>{error&&<p role="alert">{error}</p>}</div>;
}
function Recorder({onChange}){
 const [recording,setRecording]=useState(false),[heard,setHeard]=useState(''),[preparing,setPreparing]=useState(false),[clip,setClip]=useState(''),[error,setError]=useState(''),[elapsed,setElapsed]=useState(0);
 const recorder=useRef(),recognition=useRef(),stream=useRef(),alive=useRef(true),timer=useRef(),ticker=useRef();
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;clearTimeout(timer.current);clearInterval(ticker.current);if(recorder.current?.state==='recording')recorder.current.stop();try{recognition.current?.abort()}catch{}stream.current?.getTracks().forEach(t=>t.stop());}},[]);
 const stop=()=>{if(recorder.current?.state==='recording')recorder.current.stop();};
 const begin=async()=>{if(preparing||recording)return;setPreparing(true);setError('');setHeard('');try{
  if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Recording is unavailable in this browser. Open this lesson in Safari or Chrome and allow the microphone.');
  const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;
  const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));
  const r=new MediaRecorder(s,{...(mime?{mimeType:mime}:{}),audioBitsPerSecond:32000});recorder.current=r;const chunks=[];let transcript='';const started=Date.now();setClip('');onChange(null);setElapsed(0);
  r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};
  r.onerror=()=>{stop();if(alive.current)setError('Recording stopped unexpectedly. Please record again.');};
  r.onstop=()=>{clearTimeout(timer.current);clearInterval(ticker.current);s.getTracks().forEach(t=>t.stop());try{recognition.current?.stop()}catch{}if(!alive.current)return;setRecording(false);const blob=new Blob(chunks,{type:(r.mimeType||mime||'audio/mp4').split(';')[0]});const seconds=Math.min(90,(Date.now()-started)/1000);if(blob.size>1000000||blob.size<100||seconds<1){setError('The clip is empty or too large. Please record a shorter response (at least one second).');return;}const reader=new FileReader();reader.onerror=()=>{if(alive.current)setError('Could not prepare the recording. Please record again.');};reader.onload=()=>{if(alive.current){setClip(reader.result);onChange({audio:reader.result,seconds,transcript});}};reader.readAsDataURL(blob);};
  r.start();setRecording(true);ticker.current=setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),1000);timer.current=setTimeout(stop,90000);
 }catch(e){stream.current?.getTracks().forEach(t=>t.stop());setError(e.message||'Microphone access was unavailable.');}finally{if(alive.current)setPreparing(false);}};
 return <div className="skills-recorder"><button type="button" className="outline-button" disabled={preparing} onClick={recording?stop:begin}>{preparing?'Opening microphone…':recording?`Stop recording · ${elapsed}s`:clip?'Record again':'Start recording'}</button>{clip&&<audio controls src={clip}/>}{heard&&<small>Browser transcript: {heard}</small>}<small>Maximum 90 seconds. Replay before submitting. Recording stays on this page until you press Save response.</small>{error&&<p role="alert">{error}</p>}</div>;
}
function AIFeedback({submission,onUpdated,canAssess=true}){
 const [available,setAvailable]=useState(null),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;skillRequest('/ai-status').then(d=>{if(live)setAvailable(d.available)}).catch(()=>{if(live)setAvailable(false)});return()=>{live=false}},[]);
 const result=submission.result?.aiAssessment||(submission.result?.method?.endsWith('-rubric-v2')?submission.result:null);
 const assess=async()=>{if(busy||!consent)return;setBusy(true);setError('');try{const d=await skillRequest('/'+submission.id+'/assess','POST',{aiConsent:true});onUpdated({...submission,result:d.result});}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="ai-feedback"><h3>AI assessment</h3>{result?<><p><b>{result.score==null?'Not enough evidence to score':`${result.score}% · task score`}</b></p><p>{result.feedback}</p>{result.criteria?.map((c,i)=><p key={c}><b>{c}{result.ratings?.[i]!=null?` · ${result.ratings[i]}/4`:''}</b><br/>{result.evidence?.[i]}</p>)}{result.strengths?.length>0&&<><h4>What worked well</h4><ul>{result.strengths.map((v,i)=><li key={i}>{v}</li>)}</ul></>}{result.corrections?.map((c,i)=><div key={i}><p lang="es">{c.original} → <b>{c.improved}</b></p><p>{c.explanation}</p></div>)}<p><b>Next practice:</b> {result.nextStep}</p>{result.transcript&&<details><summary>Approximate transcript</summary><p lang="es">{result.transcript}</p></details>}<small>AI feedback can make mistakes. This task score is not a certified CEFR level.</small></>:canAssess?<><p>{available===null?'Checking AI availability…':available?'Get feedback on your response, with specific corrections and a next practice step.':'AI assessment is not connected yet. Your response is safely saved; you can return here once it is enabled.'}</p>{available&&<label className="skills-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={busy}/>Send this response {getSkillTask(submission.task)?.skill==='Speaking'?'and its recorded audio ':''}to OpenAI for AI assessment. This does not enable teacher sharing.</label>}<button type="button" className="primary" disabled={!available||!consent||busy} onClick={assess}>{busy?'Assessing…':available?'Get AI assessment':'AI assessment unavailable'}</button>{error&&<p role="alert">{error}</p>}</>:<p>No AI assessment requested by the learner.</p>}</div>;
}
export function ProductionResponse({task,user,assessment=null,onSaved}){
 const draftKey=`continuum-production-${user?.id||'guest'}-${assessment||'lesson'}-${task.id}`;
 const [text,setText]=useState(()=>{try{return localStorage.getItem(draftKey)||''}catch{return ''}}),[audio,setAudio]=useState(null),[saved,setSaved]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[consent,setConsent]=useState(false);
 const key=useRef(crypto.randomUUID());
 useEffect(()=>{let live=true;if(assessment)skillRequest().then(d=>{const old=d.submissions.find(s=>s.assessment===assessment&&s.task===task.id);if(live&&old){setSaved(old);onSaved?.(old);}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[assessment,task.id]);
 const submit=async()=>{if(busy)return;setBusy(true);setError('');try{const d=await skillRequest('','POST',{task:task.id,assessment,response:task.skill==='Writing'?text:audio,submissionKey:key.current});setSaved(d.submission);try{localStorage.removeItem(draftKey)}catch{}onSaved?.(d.submission);}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(saved)return <div className="skills-saved" role="status"><h3>Response saved</h3><p>{saved.result?.feedback || 'Your response is saved to your account.'}</p><p>{saved.result?.nextStep}</p><AIFeedback submission={saved} onUpdated={s=>{setSaved(s);onSaved?.(s)}}/>{saved.result?.score!=null&&<div className="ai-feedback"><strong>{saved.result.score}% · {saved.result.feedback}</strong><p><b>Next step:</b> {saved.result.nextStep}</p></div>}{!assessment&&<button className="outline-button" onClick={()=>{setSaved(null);setAudio(null);key.current=crypto.randomUUID()}}>Make another attempt</button>}</div>;
 return <section className="skills-production"><p>{task.prompt}</p><p><b>{task.skill==='Writing'?`Aim for ${task.words[0]}–${task.words[1]} words`:`Aim for about ${task.seconds} seconds`}</b> · {task.level} task</p>{task.skill==='Writing'?<><label htmlFor={`response-${task.id}`}>Your Spanish response</label><textarea id={`response-${task.id}`} lang="es" spellCheck={!assessment} disabled={busy} value={text} maxLength={6000} rows={8} onChange={e=>{setText(e.target.value);try{localStorage.setItem(draftKey,e.target.value)}catch{}}}/><small>{text.trim()?text.trim().split(/\s+/).length:0} words · draft saved on this device</small></>:<Recorder onChange={setAudio}/>}
 {task.skill==='Speaking'&&<p role="status">{audio?'Recording ready to save.':'Record your response and press Stop recording first.'}</p>}<details><summary>What the reviewer will assess</summary><ul>{rubricFor(task.skill).map(c=><li key={c}>{c}</li>)}</ul><p>Each criterion: 0 (no evidence) to 4 (consistently effective for this task). A rubric score is not a certified CEFR level.</p></details>
 <label className="skills-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Save my {task.skill==='Writing'?'writing':'recorded audio'} to my account. Connected teachers can access it only while “Share self-study activity” is on.</label>
 {!user&&<p>Sign in from Account to submit and keep this response.</p>}{!consent&&<p>To save, select the permission checkbox above. Teacher sharing is controlled separately in Account.</p>}{error&&<p role="alert">{error}</p>}<button className="primary" disabled={!user||busy||!consent||(task.skill==='Writing'?text.trim().length<10:!audio)} onClick={submit}>{busy?'Saving…':task.skill==='Speaking'?'Save speaking practice':'Save response'}</button></section>;
}
function ListeningLesson({task,user,onSaved}){
 const [answers,setAnswers]=useState({}),[result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const key=useRef(crypto.randomUUID());
 const submit=async()=>{setBusy(true);setError('');try{const response=task.questions.map((q,i)=>answers[i]);if(user){const d=await skillRequest('','POST',{task:task.id,response,submissionKey:key.current});setResult(d.submission.result);onSaved?.(d.submission);}else{const correct=response.filter((a,i)=>a===task.questions[i].answer).length;setResult({score:Math.round(correct/response.length*100),correct,total:response.length});}}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <><p>Listen for the main idea, then replay for detail. Answer before opening the transcript.</p><ListeningAudio text={task.audio}/><details><summary>Show transcript for practice</summary><p lang="es">{task.audio}</p></details>{task.questions.map((q,i)=><fieldset className="skills-options" key={i} disabled={!!result||busy}><legend>{i+1}. {q.prompt}</legend>{q.options.map((o,j)=><label key={j}><input type="radio" name={task.id+i} checked={answers[i]===j} onChange={()=>setAnswers(a=>({...a,[i]:j}))}/>{o}</label>)}{result&&<p>{answers[i]===q.answer?'Correct.':'Review: '+q.options[q.answer]+'.'} {q.note}</p>}</fieldset>)}{error&&<p role="alert">{error}</p>}{result?<div className="skills-saved"><h3>{result.score}% · {result.correct}/{result.total}</h3><p>{user?'Saved to your listening record.':'Preview result. Sign in to save future attempts.'}</p><button className="outline-button" onClick={()=>{setResult(null);setAnswers({});key.current=crypto.randomUUID()}}>Try again</button></div>:<button className="primary" disabled={busy||Object.keys(answers).length!==task.questions.length} onClick={submit}>{busy?'Saving…':'Check & save listening'}</button>}</>;
}
export function SkillRecord({user,learnerId}){
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ratings,setRatings]=useState(['','','','']),[feedback,setFeedback]=useState('');const teacher=!!learnerId;
 const load=async()=>{try{const d=await skillRequest(teacher?'/learner/'+learnerId:'');setRows(d.submissions);setError('');}catch(e){setRows([]);setSelected(null);setError(e.message);}};
 useEffect(()=>{let live=true;skillRequest(teacher?'/learner/'+learnerId:'').then(d=>{if(live)setRows(d.submissions)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[learnerId,user?.id]);
 const open=async id=>{setBusy(true);setSelected(null);setError('');try{const d=await skillRequest('/'+id);setSelected(d.submission);setRatings(d.submission.result.ratings||['','','','']);setFeedback(d.submission.result.feedback||'');}catch(e){setError(e.message)}finally{setBusy(false)}};
 const review=async()=>{setBusy(true);try{const d=await skillRequest('/'+selected.id+'/review','PUT',{ratings:ratings.map(Number),feedback});setSelected(s=>({...s,result:d.result}));await load();}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <section className="panel skills-record"><span className="eyebrow">LISTENING · WRITING · SPEAKING</span><h3>{teacher?'Review learner responses':'Your skill submissions'}</h3><button className="text-button" onClick={()=>{setSelected(null);load()}}>Refresh record</button>{error&&<p role="alert">{error}</p>}{!rows.length&&!error&&<p>No submissions yet. Complete a skill workshop or submit a test response.</p>}<div className="skills-history">{rows.map(s=><button key={s.id} onClick={()=>open(s.id)} disabled={busy}><span>{getSkillTask(s.task)?.title}<small>{new Date(s.at).toLocaleDateString()} · {s.assessment?'Level test':'Lesson'}</small></span><b>{s.result.score==null?'Saved · unscored':s.result.score+'%'}</b></button>)}</div>{selected&&<div className="skills-review">{getSkillTask(selected.task)?.skill!=='Listening'&&<AIFeedback submission={selected} canAssess={!teacher} onUpdated={s=>{setSelected(s);load()}}/>}<h4>{getSkillTask(selected.task)?.title}</h4><p>{selected.result.taskPrompt||getSkillTask(selected.task)?.prompt}</p>{selected.result?.score!=null&&<div className="ai-feedback"><strong>{selected.result.method==='listening-answer-key'?'Listening score':selected.result.status==='reviewed'?'Teacher score':'AI estimate'}: {selected.result.score}%</strong><p>{selected.result.feedback}</p><p><b>Next step:</b> {selected.result.nextStep}</p></div>}{typeof selected.response==='string'?<blockquote lang="es">{selected.response}</blockquote>:selected.response?.audio?<audio controls src={selected.response.audio}/>:null}{selected.result.feedback&&<><p><b>{selected.result.reviewer||'Feedback'}:</b> {selected.result.feedback}</p>{selected.result.score!=null&&<p>Rubric score: {selected.result.score}% · task evidence, not CEFR certification.</p>}</>}{teacher&&getSkillTask(selected.task)?.skill!=='Listening'&&<><p>Rate the response against this task’s difficulty, then give a strength and a specific next step.</p>{rubricFor(getSkillTask(selected.task).skill).map((c,i)=><label key={c}>{c}<select value={ratings[i]} onChange={e=>setRatings(r=>r.map((v,j)=>i===j?e.target.value:v))}><option value="">Select a rating</option>{rubricAnchors.map((a,j)=><option key={j} value={j}>{a}</option>)}</select></label>)}<label>Feedback<textarea value={feedback} maxLength={3000} onChange={e=>setFeedback(e.target.value)}/></label><button className="primary" disabled={busy||ratings.some(x=>x==='')||feedback.trim().length<10} onClick={review}>{busy?'Saving…':'Save teacher evaluation'}</button></>}</div>}</section>;
}
export default function SkillsWorkshop({level,user}){
 const [active,setActive]=useState(null),[revision,setRevision]=useState(0),[showRecord,setShowRecord]=useState(false);const top=useRef(null);
 useEffect(()=>{setActive(null)},[level]);
 useLayoutEffect(()=>{if(active)top.current?.scrollIntoView({block:'start',behavior:'instant'})},[active]);
 const task=getSkillTask(active);
 return <section className="skills-workshop" ref={top}><div className="section-title"><div><span className="eyebrow">{level} · COMMUNICATION WORKSHOPS</span><h2>Listen. Write. Speak.</h2><p>Build real responses, beyond choosing an answer.</p></div></div>{task?<section className="panel" key={task.id}><button className="back" onClick={()=>setActive(null)}>← All skill workshops</button><span className="eyebrow">{task.level} · {task.skill}</span><h2>{task.title}</h2><h3>{task.topic}</h3>{task.skill==='Listening'?<ListeningLesson task={task} user={user} onSaved={()=>setRevision(n=>n+1)}/>:<><ol>{task.tips.map(t=><li key={t}>{t}</li>)}</ol><details><summary>Study a model, then create your own response</summary><p lang="es">{task.model}</p><ListeningAudio text={task.model}/><p>Notice the organisation and linking words. The model is a short structure example, not the required response length. Use your own details.</p></details><ProductionResponse task={task} user={user} onSaved={()=>setRevision(n=>n+1)}/></>}</section>:<div className="skills-cards">{skillTasks.filter(t=>t.level===level).map(t=><button key={t.id} onClick={()=>setActive(t.id)}><span className="eyebrow">{t.skill}</span><h3>{t.title}</h3><p>{t.topic}</p><b>{t.skill==='Listening'?'Listen & answer':t.skill==='Writing'?'Compose & submit':'Record & submit'} →</b></button>)}</div>}{user&&<><button className="outline-button" onClick={()=>setShowRecord(x=>!x)}>{showRecord?'Hide':'View'} skill submissions & feedback</button>{showRecord&&<SkillRecord key={revision} user={user}/>}</>}</section>;
}
