import {internationalSkills,internationalProductionSkills} from './international-course.mjs';
// Original CEFR-inspired tasks. Course bands are editorial, not validated cut scores.
export const skillLevels=['A1','A2','B1','B2','C1'];
const units=[
 {level:'A1',topic:'Introduce yourself and make a simple plan',words:[30,60],seconds:30,
  writing:'Write a message to a new classmate. Introduce yourself, say where you live, and suggest a time to study together.',
  speaking:'Introduce yourself to a new classmate. Say where you live, describe one thing you enjoy, and ask them one question.',
  tips:['Use short sentences: Me llamo…, Vivo en…, Me gusta…','Add a clear invitation with a day or time.','Check person endings: vivo, vives; me gusta + singular noun or infinitive.'],
  model:'Hola, me llamo Sara y vivo en Valencia. Me gusta cocinar. Estudio español por la tarde. ¿Quieres estudiar conmigo el lunes a las cinco? Podemos ir a la biblioteca. ¿Qué día te viene bien?',
  audio:'Hola, soy Elena. La clase de español es el martes a las seis. Nos vemos en la biblioteca, al lado del parque. Trae un cuaderno. No necesitas comprar un libro.',
  items:[['¿Cuándo es la clase?',['El martes a las seis.','El lunes a las cinco.','El martes a las siete.'],0,'El martes a las seis gives both the day and time.'],['¿Dónde se encuentran?',['En el parque.','En la biblioteca.','En una tienda.'],1,'The library is the meeting place; the park is only a landmark.'],['¿Qué hay que llevar?',['Un libro nuevo.','Una entrada.','Un cuaderno.'],2,'Trae un cuaderno states what to bring.']]},
 {level:'A2',topic:'Change a plan and tell what happened',words:[60,100],seconds:45,
  writing:'Write to a friend. Explain why you missed yesterday’s meeting, describe what happened, and propose a new day and activity.',
  speaking:'Leave a voice message for a friend. Explain why you missed a meeting yesterday and suggest a new plan. End with a question.',
  tips:['Organise the message: apology → past event → new plan.','Use ayer + past forms; voy a / podemos for a new plan.','Connect short ideas with porque, pero and después.'],
  model:'Hola, Luis. Perdona por no llegar ayer. Salí de casa a tiempo, pero el autobús no pasó. Esperé media hora y después volví a casa. ¿Podemos vernos el sábado? Voy a estar en el centro. Podemos comer y pasear por el mercado. Dime si te viene bien.',
  audio:'Hola, Marta. Ayer no pude reservar mesa en el restaurante del centro. He reservado en el de la estación para el sábado a las dos. Antes pensábamos ir al cine, pero ahora vamos a comer primero. Llámame si prefieres otra hora.',
  items:[['¿Dónde van a comer?',['En casa de Marta.','En el restaurante del centro.','En el restaurante de la estación.'],2,'The original central restaurant was unavailable.'],['¿Qué harán primero?',['Comer.','Ir al cine.','Reservar otra mesa.'],0,'Ahora vamos a comer primero changes the earlier sequence.'],['¿Para qué debe llamar Marta?',['Para cancelar el cine.','Para proponer otra hora.','Para pedir la dirección.'],1,'The call is conditional on preferring a different time.']]},
 {level:'B1',topic:'Explain a problem and negotiate a solution',words:[100,150],seconds:60,
  writing:'Write to your accommodation host. Describe a problem with the room, explain its effect on your stay, and request a realistic solution politely.',
  speaking:'You booked a quiet room, but it is noisy. Explain the problem to the host, describe its effect, propose two possible solutions and say which you prefer.',
  tips:['Give a specific example rather than only saying it is bad.','Connect cause and effect with porque / por eso.','Use ¿Sería posible…? or ¿Podría…? for a polite solution.'],
  model:'Hola, gracias por recibirme. La habitación está limpia, pero el ruido de la calle no me deja dormir. Anoche continuó hasta las dos y mañana tengo que trabajar temprano. ¿Sería posible cambiar a una habitación interior? Si no hay ninguna libre, podría trasladarme mañana. Preferiría quedarme aquí porque la ubicación me resulta muy cómoda. Gracias por buscar una solución.',
  audio:'El centro deportivo cerrará la piscina durante dos semanas para reparar el techo. Las clases de natación se trasladan al centro del barrio vecino, sin coste adicional. Quienes no puedan desplazarse podrán recuperar las clases el mes siguiente. La sala de máquinas seguirá abierta.',
  items:[['¿Por qué cierra la piscina?',['Para reparar el techo.','Por falta de profesores.','Para cambiar las máquinas.'],0,'The roof repair causes the closure.'],['¿Qué pasa con las clases trasladadas?',['Se pagan dos veces.','No tienen coste adicional.','Solo se ofrecen el mes siguiente.'],1,'Sin coste adicional means no extra charge.'],['¿Qué opción tienen quienes no puedan desplazarse?',['Perder las clases.','Usar la sala de máquinas como piscina.','Recuperarlas el mes siguiente.'],2,'Recovery next month is a separate alternative.']]},
 {level:'B2',topic:'Weigh alternatives and defend a recommendation',words:[150,220],seconds:75,
  writing:'Write a proposal to your workplace comparing remote work with office work. Discuss a benefit and a drawback of each, recommend a mixed policy, and address a likely objection.',
  speaking:'Your town is considering restricting cars in the centre. Present benefits and drawbacks, respond to a shopkeeper’s concern, and recommend a workable policy.',
  tips:['State a position, support it, then acknowledge a counterargument.','Use aunque / sin embargo / siempre que to qualify a claim.','Finish with a concrete recommendation and a condition for success.'],
  model:'El trabajo remoto permite concentrarse y evita desplazamientos; sin embargo, puede dificultar la coordinación. La oficina facilita las conversaciones espontáneas, aunque no todas las tareas requieren presencia. Propongo dos días comunes y flexibilidad el resto de la semana. Quienes temen perder contacto tendrían reuniones breves y un horario compartido. La medida debería revisarse tras tres meses, teniendo en cuenta tanto los resultados como la experiencia del equipo.',
  audio:'La asociación apoya ampliar el horario de la biblioteca, aunque considera insuficiente abrir solo los sábados. Según su portavoz, sería más útil mantenerla abierta dos noches entre semana. Reconoce que contratar personal cuesta dinero, pero propone probar el horario durante tres meses antes de decidir si se mantiene. No pide una ampliación permanente sin evaluación.',
  items:[['¿Qué cambio prefiere la asociación?',['Abrir únicamente los sábados.','Abrir dos noches entre semana.','Cerrar durante tres meses.'],1,'The preference follows sería más útil.'],['¿Cómo aborda el coste?',['Niega que exista.','Pide trabajar sin sueldo.','Propone una prueba limitada.'],2,'A pilot limits the commitment before a decision.'],['¿Qué postura adopta?',['Apoyo condicionado a una evaluación.','Rechazo de cualquier cambio.','Ampliación permanente inmediata.'],0,'It supports change while requiring evaluation.']]},
 {level:'C1',topic:'Synthesise evidence and qualify your position',words:[220,300],seconds:90,
  writing:'Write a briefing for a city council. Evidence A: a pilot cycle lane increased cycling by 20%. Evidence B: some local shops reported fewer customers, but no comparison area was studied. Weigh what can and cannot be concluded, propose a decision, and specify further evidence needed.',
  speaking:'A university says online courses widened access, but student completion fell. Give a nuanced recommendation: distinguish possible explanations from established facts, anticipate a counterargument, and propose how to evaluate a change.',
  tips:['Distinguish association from cause and identify missing evidence.','Structure competing claims with si bien, cabe matizar and en conjunto.','Make the recommendation proportionate to the evidence and audience.'],
  model:'Si bien el aumento del uso de la bicicleta es alentador, no basta para atribuir todos los cambios al carril. La caída de clientes declarada por algunos comercios merece atención, aunque la ausencia de una zona de comparación impide establecer causalidad. Conviene mantener provisionalmente la intervención y recopilar datos comparables de movilidad y ventas. Una revisión con criterios publicados permitiría ajustar el diseño sin presentar conclusiones todavía inciertas como definitivas.',
  audio:'La investigadora considera alentadora la caída del consumo energético, pero advierte que coincidió con un invierno excepcionalmente suave. No descarta que las ayudas hayan contribuido; cuestiona que pueda atribuirse a ellas toda la reducción. Sugiere comparar hogares semejantes que no recibieron ayudas y observar varios inviernos. A su juicio, retirar el programa ahora sería tan precipitado como declararlo un éxito definitivo.',
  items:[['¿Qué cuestiona la investigadora?',['Que el consumo haya bajado.','La atribución de toda la caída a las ayudas.','Que el invierno fuera suave.'],1,'She disputes the causal attribution, not the observed decrease.'],['¿Qué función tiene comparar hogares?',['Anunciar el éxito definitivo.','Eliminar todos los datos.','Distinguir el efecto de las ayudas de otros factores.'],2,'Comparable households provide evidence about alternative explanations.'],['¿Qué recomienda implícitamente?',['Seguir evaluando antes de una decisión definitiva.','Retirar de inmediato el programa.','Ignorar el clima.'],0,'Both immediate withdrawal and definitive success are called premature.']]}
];
export const skillTasks=units.flatMap(u=>['Listening','Writing','Speaking'].map(skill=>({id:`skills-${u.level.toLowerCase()}-${skill.toLowerCase()}`,level:u.level,skill,title:skill==='Listening'?`Listen for meaning · ${u.level}`:skill==='Writing'?`Write with purpose · ${u.level}`:`Speak in your own words · ${u.level}`,topic:u.topic,prompt:u[skill.toLowerCase()]||'Listen once for the main idea, then again for details. Answer before opening the transcript.',tips:u.tips,model:u.model,words:u.words,seconds:u.seconds,audio:u.audio,questions:u.items.map(([prompt,options,answer,note])=>({prompt,options,answer,note}))})));
skillTasks.push(...internationalSkills,...internationalProductionSkills);
export const getSkillTask=id=>skillTasks.find(t=>t.id===id);
export const rubricFor=skill=>skill==='Writing'?['Task fulfilment','Organisation and cohesion','Vocabulary and register','Grammatical control']:['Task fulfilment','Fluency and coherence','Vocabulary and grammar','Intelligibility'];
export const rubricAnchors=['0 · No assessable evidence','1 · Limited; frequent support needed','2 · Partly effective; meaning sometimes unclear','3 · Effective for the task; some lapses','4 · Consistently effective and clear'];
