import {beginStroke,moveStroke,endStroke} from './drawing-pad.mjs';
import React,{useState} from 'react';
import SentenceAudio from './SentenceAudio.jsx';
import './sound-script.css';
export default function SoundScriptReference({lesson}){
 const [hidden,setHidden]=useState(false),[selected,setSelected]=useState(0),[strokes,setStrokes]=useState([]);
 if(!lesson.soundGuide&&!lesson.characters)return null;
 const characters=lesson.characters;const active=characters?.[selected];
 return <section className="sound-script"><span className="eyebrow">{characters?'LOOK → LISTEN → RECALL':'LISTEN → SHAPE → REPEAT → COMPARE'}</span><h2>{characters?'Character studio':'Your sound studio'}</h2>
 {lesson.soundGuide&&<><p>Listen to each word, repeat it slowly, then say the full model phrase below. Record yourself and compare one feature at a time.</p><div className="sound-pairs">{lesson.soundGuide.pairs.map(([a,b])=><article key={a}><strong lang={lesson.locale}>{a}</strong><SentenceAudio text={a} lang={lesson.locale}/><p>{b}</p>{!/[A-Z /:]/.test(b)&&<SentenceAudio text={b} lang={lesson.locale}/>}</article>)}</div>{lesson.title==='Tap and trill'&&<article className="sound-pairs"><div><strong lang="es">rojo</strong><p>Word-initial r: begin with a trill, as in perro.</p><SentenceAudio text="rojo" lang="es-ES"/></div></article>}<ol><li>Notice tongue position, airflow or the timing described above.</li><li>Repeat each word three times with a relaxed voice.</li><li>Say the model phrase with natural pauses.</li><li>Listen to your recording. Choose one feature to improve and try again.</li></ol><p className="reference-hint">Human recordings are labelled with their speaker and source. Other model audio is AI-generated. Regional pronunciation varies. Speech recognition checks recognized words; it does not grade individual sounds or pitch accent.</p></>}
 {characters&&<><p>Select a character, then press Listen. Isolated kana are spoken twice with a pause. Use 0.85× to listen more slowly without changing pitch. Hide the readings to test recall.</p><p className="reference-hint">Kana audio: human recordings from <a href="https://funjapaneselearning.com" target="_blank" rel="noreferrer">FUN Japanese Learning</a>, distributed in <a href="https://huggingface.co/datasets/arsalan-anwari/kana-sounds" target="_blank" rel="noreferrer">Kana Sounds by Arsalan Anwari</a> under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>. Pauses and repetition added. Other audio is labelled by source.</p><button type="button" aria-pressed={hidden} onClick={()=>setHidden(!hidden)}>{hidden?'Show readings':'Hide readings'}</button><div className="kana-grid">{characters.map((x,i)=><button type="button" key={x.glyph} aria-pressed={selected===i} onClick={()=>{setSelected(i);setStrokes([]);}}><strong lang="ja">{x.glyph}</strong><span>{hidden?'—':x.reading}</span>{x.meaning&&<small>{x.meaning}</small>}</button>)}</div><div className="copy-studio"><div><h3>Copy {active.glyph}</h3><SentenceAudio text={active.meaning?active.reading:active.glyph} lang="ja-JP"/><p>Trace or copy with a finger or pointer. This is an optional shape practice pad, without handwriting scoring or stroke-order guidance. The exercises also support typed answers.</p><button type="button" onClick={()=>setStrokes([])}>Clear drawing</button></div><svg viewBox="0 0 300 300" role="img" aria-label={`Optional copying pad for ${active.glyph}`} onPointerDown={e=>beginStroke(e,setStrokes)} onPointerMove={e=>moveStroke(e,setStrokes)} onPointerUp={endStroke} onPointerCancel={endStroke}><path d="M150 0V300M0 150H300" stroke="#d9d5e9" strokeDasharray="5 5"/><text x="150" y="215" textAnchor="middle" fontSize={active.glyph.length>1?115:210} fill="#e0dced" lang="ja">{active.glyph}</text>{strokes.map((s,i)=><polyline key={i} points={s.join(' ')} fill="none" stroke="#6550b7" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/>)}</svg></div></>}
 </section>;
}
