// New scenarios have independent IDs; existing attempts and drafts are unchanged.
export const visualChapters=[],visualLessons=[],visualTransfer={};
const locales={es:'es-ES',pt:'pt-BR',en:'en-US',ja:'ja-JP'};
const scenes=[
 {key:'cafe',level:'A1',title:'A café order, step by step',theme:'cafe',goal:'Order a drink, choose a size and ask for the bill.',lines:{es:['Quisiera un café con leche, por favor.','Pequeño, para llevar.','La cuenta, por favor.'],pt:['Eu queria um café com leite, por favor.','Pequeno, para viagem.','A conta, por favor.'],en:['I would like a coffee with milk, please.','A small one, to take away.','Could I have the bill, please?'],ja:['カフェラテを一つください。','小さいサイズで、持ち帰りでお願いします。','お会計をお願いします。']},meanings:['A polite request for coffee with milk.','A small drink to take away.','A request to pay the bill.'],focus:['Notice how the request is softened.','Size and takeaway preference add useful details.','Finish the exchange with a polite request.'],checks:[['What drink is requested?',['Coffee with milk','Tea without milk','A glass of water']],['Where will the drink be consumed?',['Away from the café','At a reserved table','The customer does not specify']],['What does the final line request?',['The bill','Another drink','The menu']]],words:{es:[['un café con leche','coffee with milk'],['pequeño','small'],['para llevar','to take away'],['la cuenta','the bill']],pt:[['um café com leite','coffee with milk'],['pequeno','small'],['para viagem','to take away'],['a conta','the bill']],en:[['coffee with milk','coffee with milk'],['small','small'],['to take away','to take away'],['the bill','the bill']],ja:[['カフェラテ','coffee with milk'],['小さい','small'],['持ち帰り','to take away'],['お会計','the bill']]}},
 {key:'station',level:'A2',title:'A change of platform',theme:'station',goal:'Follow a travel update and check the new departure point.',lines:{es:['El tren sale a las diez y media.','Hoy sale del andén cuatro, no del dos.','¿Este billete sirve para ese tren?'],pt:['O trem sai às dez e meia.','Hoje sai da plataforma quatro, não da dois.','Esta passagem vale para esse trem?'],en:['The train leaves at half past ten.','Today it leaves from platform four, not two.','Is this ticket valid for that train?'],ja:['電車は十時半に出発します。','今日は二番線ではなく、四番線から出発します。','この切符でその電車に乗れますか。']},meanings:['The departure time is 10:30.','The departure platform has changed to platform four.','A passenger checks whether their ticket can be used.'],focus:['Identify the precise time.','A correction contrasts the old detail with the new one.','Check validity before boarding.'],checks:[['What is the departure time?',['10:30','10:00','11:30']],['Which platform should the passenger use today?',['Platform four','Platform two','No platform is announced']],['What does the passenger want to check?',['Whether the ticket is valid','Whether the train has arrived','Whether the station is closed']]],words:{es:[['el tren','the train'],['el andén','the platform'],['el billete','the ticket'],['diez y media','half past ten']],pt:[['o trem','the train'],['a plataforma','the platform'],['a passagem','the ticket'],['dez e meia','half past ten']],en:[['the train','the train'],['the platform','the platform'],['valid','usable for this journey'],['half past ten','10:30']],ja:[['電車','the train'],['四番線','platform four'],['切符','the ticket'],['十時半','half past ten']]}},
 {key:'meeting',level:'B1',title:'Renegotiate a deadline',theme:'work',goal:'Explain a delay, propose a deadline and make a commitment.',lines:{es:['Todavía no he terminado el informe.','¿Podríamos entregarlo el viernes en lugar del jueves?','Te enviaré un borrador mañana.'],pt:['Ainda não terminei o relatório.','Poderíamos entregar na sexta em vez de quinta?','Vou te enviar um rascunho amanhã.'],en:['I have not finished the report yet.','Could we submit it on Friday instead of Thursday?','I will send you a draft tomorrow.'],ja:['報告書はまだ完成していません。','木曜日ではなく、金曜日に提出してもいいでしょうか。','明日、下書きを送ります。']},meanings:['The report is unfinished.','A later deadline is proposed, not confirmed.','The speaker commits to sending a draft tomorrow.'],focus:['Separate current status from a finished action.','A polite proposal leaves room for a reply.','An interim commitment makes the request more useful.'],checks:[['What is the report’s current status?',['Unfinished','Already submitted','Cancelled']],['What new deadline is proposed?',['Friday','Thursday','Tomorrow morning']],['What is promised for tomorrow?',['A draft','A signed contract','A completed presentation']]],words:{es:[['el informe','the report'],['un borrador','a draft'],['en lugar de','instead of'],['todavía no','not yet']],pt:[['o relatório','the report'],['um rascunho','a draft'],['em vez de','instead of'],['ainda não','not yet']],en:[['the report','the report'],['a draft','a preliminary version'],['instead of','as a replacement for'],['not yet','not completed so far']],ja:[['報告書','the report'],['下書き','a draft'],['提出する','to submit'],['まだ完成していない','not finished yet']]}},
 {key:'city',level:'B2',title:'A neighbourhood proposal',theme:'city',goal:'Weigh a benefit against a practical concern and suggest a trial.',lines:{es:['Una zona peatonal podría reducir el ruido.','Sin embargo, algunos comercios dependen de las entregas diarias.','Propongo probar la medida durante tres meses antes de ampliarla.'],pt:['Uma área para pedestres poderia reduzir o barulho.','No entanto, algumas lojas dependem de entregas diárias.','Proponho testar a medida por três meses antes de ampliá-la.'],en:['A pedestrian zone could reduce noise.','However, some shops depend on daily deliveries.','I propose testing the measure for three months before expanding it.'],ja:['歩行者専用区域を設ければ、騒音を減らせるかもしれません。','しかし、毎日の配達に頼っている店もあります。','拡大する前に、三か月間試してみることを提案します。']},meanings:['Noise reduction is presented as a possibility.','Delivery access is raised as a concern.','A three-month trial is proposed before expansion.'],focus:['Possibility is weaker than a guarantee.','The concern qualifies the proposal rather than cancelling it.','A trial allows evidence to inform the next decision.'],checks:[['How certain is the claimed noise benefit?',['Possible, not guaranteed','Guaranteed','Already measured']],['Which concern is raised?',['Daily deliveries to shops','School exam results','Train ticket prices']],['What should happen before expansion?',['A three-month trial','Immediate permanent closure','No further action']]],words:{es:[['una zona peatonal','a pedestrian zone'],['el ruido','noise'],['las entregas diarias','daily deliveries'],['ampliar','to expand']],pt:[['uma área para pedestres','a pedestrian area'],['o barulho','noise'],['as entregas diárias','daily deliveries'],['ampliar','to expand']],en:[['a pedestrian zone','an area mainly for people on foot'],['noise','unwanted sound'],['daily deliveries','goods brought each day'],['to expand','to make larger']],ja:[['歩行者専用区域','a pedestrian-only zone'],['騒音','noise'],['配達','delivery'],['拡大する','to expand']]}},
 {key:'evidence',level:'C1',title:'Read a claim critically',theme:'study',goal:'Distinguish a reported relationship from a causal conclusion.',lines:{es:['El estudio detectó una relación entre ambas variables.','Eso no demuestra por sí solo que una sea la causa de la otra.','Conviene contrastar los resultados con otras fuentes antes de sacar conclusiones.'],pt:['O estudo identificou uma relação entre as duas variáveis.','Isso, por si só, não demonstra que uma seja a causa da outra.','Convém comparar os resultados com outras fontes antes de tirar conclusões.'],en:['The study found an association between the two variables.','That alone does not demonstrate that one causes the other.','The findings should be checked against other sources before drawing conclusions.'],ja:['その研究では、二つの変数の間に関連が見られました。','それだけで、一方が他方の原因だと証明されたわけではありません。','結論を出す前に、ほかの資料と照らし合わせる必要があります。']},meanings:['An association is reported.','Causation has not been established by that fact alone.','Independent comparison is recommended before a conclusion.'],focus:['Identify exactly what the evidence supports.','A limitation narrows the claim without dismissing the study.','A cautious conclusion includes verification.'],checks:[['What did the study report?',['An association','Proof of causation','No relationship of any kind']],['What does the second line do?',['Limits the causal claim','Rejects all research','Guarantees the conclusion']],['What is the recommended next step?',['Compare with other sources','Ignore the findings','Publish an absolute claim']]],words:{es:[['una relación','an association'],['por sí solo','by itself'],['contrastar','to cross-check'],['sacar conclusiones','to draw conclusions']],pt:[['uma relação','an association'],['por si só','by itself'],['comparar','to compare'],['tirar conclusões','to draw conclusions']],en:[['an association','an observed relationship'],['causation','one factor bringing about another'],['to cross-check','to verify using another source'],['to draw conclusions','to decide what evidence implies']],ja:[['関連','an association'],['原因','a cause'],['照らし合わせる','to cross-check'],['結論を出す','to draw a conclusion']]}}
];
for(const language of Object.keys(locales))for(const scene of scenes){
 const id=`${language}-visual-v1-${scene.key}`,chapter=id+'-chapter',locale=locales[language],lines=scene.lines[language],words=scene.words[language];
 const meta={language,locale,specialist:true,curriculumVersion:2};
 const questions=scene.checks.map(([prompt,options],i)=>({prompt,options,answer:0,note:scene.meanings[i]+' '+scene.focus[i],audio:lines[i],audioLocale:locale,sourceLesson:id}));
 questions.push(...words.map(([term,meaning],i)=>({prompt:`Which expression in this scene means “${meaning}”?`,options:[term,...words.filter((_,j)=>j!==i).slice(0,2).map(x=>x[0])],answer:0,note:`${term}: ${meaning}.`,optionsLang:locale,sourceLesson:id})));
 questions.push({type:'text',prompt:`Write the expression from the scene for “${words[0][1]}”.`,answer:words[0][0],note:`The scene uses ${words[0][0]}.`,sourceLesson:id});
 const qs=questions.map((q,i)=>{if(!q.options)return q;const shift=i%q.options.length;return {...q,options:[...q.options.slice(shift),...q.options.slice(0,shift)],answer:(q.answer-shift+q.options.length)%q.options.length};});
 const visualStory={theme:scene.theme,frames:lines.map((line,i)=>({label:['Notice','Connect','Use it'][i],text:line,meaning:scene.meanings[i],note:scene.focus[i]}))};
 visualChapters.push({id:chapter,level:scene.level,title:scene.title,goal:scene.goal,kind:'Visual stories',...meta});
 const lesson={id,chapter,level:scene.level,title:scene.title,skill:'Listening',minutes:12,explanation:scene.goal,example:lines[0],visualStory,vocabulary:words.map(([term,meaning])=>({term,meaning,phrase:term,example:lines.find(x=>x.toLowerCase().includes(term.toLowerCase()))||term,translation:scene.meanings[lines.findIndex(x=>x.toLowerCase().includes(term.toLowerCase()))]||meaning})),questions:qs,...meta};
 visualLessons.push(lesson);visualTransfer[chapter]=qs.filter(q=>q.options);
 visualLessons.push({id:id+'-checkpoint',chapter,level:scene.level,title:'Scene checkpoint',skill:'Checkpoint',minutes:6,checkpoint:true,explanation:'Recall the details and expressions from the visual story.',example:scene.goal,questions:qs.filter(q=>q.options),...meta});
}
